### ISSUE TITLE
升级到2.2.2版本后，报错

### ISSUE THREAD

**Issue by qq570026938** [liujingxing/okhttp-RxHttp#104]
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.xs.qreader, PID: 13890
    java.lang.NoSuchMethodError: No static method edit$default(Lokhttp3/internal/cache/DiskLruCache;Ljava/lang/String;JILjava/lang/Object;)Lokhttp3/internal/cache/DiskLruCache$Editor; in class Lokhttp3/internal/cache/DiskLruCache; or its super classes (declaration of 'okhttp3.internal.cache.DiskLruCache' appears in /data/app/com.xs.qreader-1/base.apk:classes3.dex)
        at rxhttp.wrapper.cookie.CookieStore.saveCookie(CookieStore.kt:79)

**Comment by liujingxing** [comment]
升级后，内部使用了最新的okhttp 4.6.0版本，如你使用不是最新版本，需要告知rxhttp，内部才会兼容，详情查看https://github.com/liujingxing/okhttp-RxHttp#api%E5%85%BC%E5%AE%B9

**Comment by qq570026938** [comment]
嗯，我这个配置上了，参考的demo上的配置，还是报错，是因为我用的kotlin 配置不一样吗

> 升级后，内部使用了最新的okhttp 4.6.0版本，如你使用不是最新版本，需要告知rxhttp，内部才会兼容，详情查看https://github.com/liujingxing/okhttp-RxHttp#api%E5%85%BC%E5%AE%B9

**Comment by liujingxing** [comment]
RxHttp.setDebug(true)设置后，过滤RxHttp，看看日志输出的okhttp版本号多少

**Comment by qq570026938** [comment]
> RxHttp.setDebug(true)设置后，过滤RxHttp，看看日志输出的okhttp版本号多少

05-18 15:39:32.531 15700-15700/com.xs.qreader D/RxHttp: <------ rxhttp/2.2.2 okhttp/3.12.6 request start Method=GET ------>

**Comment by liujingxing** [comment]
我这边再次试了下3.12.6版本是ok的，方便的话加下我qq 327744707

**Comment by qq570026938** [comment]
> 327744707
好，加了

**Comment by liujingxing** [comment]
`RxHttp v2.2.3`版本已解决，感谢反馈
