### ISSUE TITLE
请问如何post请求body使用byte[]作为参数提交?

### ISSUE THREAD

**Issue by RanchoYue** [liujingxing/okhttp-RxHttp#105]

**Comment by RanchoYue** [comment]
//类似完成okHttp的如下设置
 byte[] content = new byte[10];
 Request request = new Request.Builder()
         .url(url)
         .post(FormBody.create(MediaType.parse("application/json"), content))
         .build();

**Comment by liujingxing** [comment]
对于json请求，使用postJson方法即可；但是该方式，没有直接传递byte[]参数的方法，不知道你这个byte[]是如何拿到的，如果是加密后的byte[]，建议你自定义Param，重写getRequestBody()，里面可以拿到你添加的所有参数，然后加密发送即可。详情参考https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param
