### ISSUE TITLE
data==null 走error监听，也有一些接口不需要后台返回值的

### ISSUE THREAD

**Issue by folinwu2296** [liujingxing/okhttp-RxHttp#106]
data==null 走error监听，也有一些接口不需要后台返回值的

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8

**Comment by zhaoxiuyu** [comment]
更新会不会太频繁了。都不敢用  @liujingxing

**Comment by liujingxing** [comment]
稳定版就是最新版，更新是因为有需求，极少版本是为了修改bug而更新的，最近的更新主要都是为了兼容okhttp版本，看看更新日志就知道了。接下去一段时间，都会保持1-2周一个版本，这是常态。
