### ISSUE TITLE
RxHttp.get().asxxx方法找不到怎么回事？

### ISSUE THREAD

**Issue by mrcoderzou** [liujingxing/okhttp-RxHttp#109]
RxHttp.get().asxxx方法找不到怎么回事？

**Comment by liujingxing** [comment]
查看上手准备https://github.com/liujingxing/okhttp-RxHttp#%E4%B8%8A%E6%89%8B%E5%87%86%E5%A4%87%E5%BF%85%E7%9C%8B

**Comment by mrcoderzou** [comment]
忘记设置最低api版本为21了，已经解决，非常感谢
