### ISSUE TITLE
ResponseParser 为啥我用腾讯bulg 报这个错很多

### ISSUE THREAD

**Issue by zhangheshuai** [liujingxing/okhttp-RxHttp#110]
com.laibai.http.parse.ResponseParser.onParse(ResponseParser.java:32)
--
2 rxhttp.ObservableHttp.execute(ObservableHttp.java:118)
3 rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:67)
4 io.reactivex.Observable.subscribe(Observable.java:12267)
5 io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
6 io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
7 io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
8 io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
9 java.util.concurrent.FutureTask.run(FutureTask.java:266)
10 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
11 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
13 java.lang.Thread.run(Thread.java:764)

**Comment by liujingxing** [comment]
rxhttp版本多少？光有错误栈无法定位，具体什么异常？空指针？

**Comment by zhangheshuai** [comment]
应该不是崩溃 就是看腾讯bulg 上面的错误 用的版本是 2.1.1

**Comment by liujingxing** [comment]
看下你上传错误的代码

**Comment by zhangheshuai** [comment]
Beta.canShowUpgradeActs.add(MainActivity.class);
            Beta.showInterruptedStrategy = true;
            Beta.autoCheckUpgrade = true;
            Beta.upgradeCheckPeriod = 60 * 1000;
            Bugly.setUserId(mApp,Constant.userId);
就是腾讯的正常初始化
![1590995717057](https://user-images.githubusercontent.com/17810930/83384877-bd48ef00-a41a-11ea-811e-26d40446ad79.jpg)

**Comment by liujingxing** [comment]
其实我想看的是，你在ResponseParser类中上传错误的代码，看看你怎么判断错误的。

**Comment by zhangheshuai** [comment]
ResponseParser 并没有上传错误

**Comment by liujingxing** [comment]
确定bugly上的是错误，不是崩溃吗？我记得错误是要主动上报才有的吧。

**Comment by zhangheshuai** [comment]
崩溃是崩溃 错误是错误 我在崩溃里面没有发现这些解析的问题 但是在错误里面发现好多

**Comment by liujingxing** [comment]
所以我就好奇了，错误在我印象中是要主动上报的。没有具体的异常，我无法定位问题，加我QQ吧

**Comment by zhangheshuai** [comment]
由于腾讯上传错误写的位置 导致错误很多 框架本身没有问题 报的错都是自己测试后台解析数据或者别的问题
