### ISSUE TITLE
更新2.2.5后，Url报错

### ISSUE THREAD

**Issue by taoczZYC** [liujingxing/okhttp-RxHttp#111]
![WeChat5d3ef9010f4be6dd6d92e2daa1a4f20c](https://user-images.githubusercontent.com/11548042/83474164-e66e8b80-a4bd-11ea-89f5-79fb2f26d952.png)
当存在多个@Domain
会报@Domain annotation className cannot be the same
![WeChat4e1d8a5376758058ece0dae9fad4f160](https://user-images.githubusercontent.com/11548042/83474400-80363880-a4be-11ea-8bb6-f4a399b0807d.png)

去掉多个，只保留一个Domain
仍旧报错
javax.annotation.processing.FilerException: Attempt to recreate a file for type rxhttp.wrapper.param.RxHttp

**Comment by liujingxing** [comment]
这是2.2.5版本的一个bug，用到多个Domain注解，没有指定className字段时，就会报错。至于第二个问题，应该跟环境有关系，暂时还没找到具体的原因。

**Comment by liujingxing** [comment]
该问题已在v2.2.6版本中修复，更新日志查看：https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97
