### ISSUE TITLE
数据解析

### ISSUE THREAD

**Issue by huangzhuhua666** [liujingxing/okhttp-RxHttp#112]
![image](https://user-images.githubusercontent.com/29309451/83476457-69461500-a4c3-11ea-8226-91c47aaa024d.png)
![image](https://user-images.githubusercontent.com/29309451/83476468-6f3bf600-a4c3-11ea-8aea-b826fce389a9.png)
![image](https://user-images.githubusercontent.com/29309451/83476490-7d8a1200-a4c3-11ea-9bc8-4874219442f6.png)
![image](https://user-images.githubusercontent.com/29309451/83476499-837ff300-a4c3-11ea-8f41-366cd1c99e18.png)
![image](https://user-images.githubusercontent.com/29309451/83476507-87137a00-a4c3-11ea-8ccd-382d83f68efd.png)
![image](https://user-images.githubusercontent.com/29309451/83476518-8d095b00-a4c3-11ea-8a6f-c8ef82516348.png)
像这种接口返回的字段不固定的，有没有什么办法能统一解析呢

**Comment by liujingxing** [comment]
这个没有很好的办法，只能用笨的办法。第一就是用@SerializedName注解，具体用法自己百度下；第二个就是找共同点，把code提取到BaseResponse，然后其它类继承BaseResponse。

**Comment by huangzhuhua666** [comment]
然而这个并没有太多共同点，就很随意。目前想到的就是把json处理一下，把除了code、message之外的字段包装一层data

**Comment by liujingxing** [comment]
嗯，只能具体情况具体分析了，没办法做到完全统一
