### ISSUE TITLE
关于缓存

### ISSUE THREAD

**Issue by folinwu2296** [liujingxing/okhttp-RxHttp#113]
缓存可以设置为，先从缓存获取再从从服务器获取数据

**Comment by liujingxing** [comment]
支持，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E7%BC%93%E5%AD%98%E7%AD%96%E7%95%A5

**Comment by lovedren** [comment]
先读取缓存，读取成功，直接返回；否则将请求网络(请求成功，写入缓存)

**Comment by liujingxing** [comment]
第五章节https://juejin.im/post/5dff3c2de51d45582c27cea6#heading-8
