### ISSUE TITLE
协程使用成功时使用msg

### ISSUE THREAD

**Issue by NeVaDaAAA** [liujingxing/okhttp-RxHttp#116]
非常棒的库 作者我这边有个疑问
点赞接口
服务器返回为
{
	"code": 200,
	"msg": "点赞成功",
	"path": "",
	"data": {},
	"extra": {},
	"timestamp": "1592873459756"
}
成功时需要使用msg字段,如何实现呢

以下为代码
fun changeFollow(paramsMap: Map<String, String>) = rxLifeScope.launch({
        val result=RxHttp.postJson(ApiConstants.CHANGE_FOLLOW)
            .addAll(paramsMap)
            .toResponse<String>()
            .await()
        followStatus.value = ???(msg该如何取呢)
    }, {
        followErr.value = it.errorMsg
    })

**Comment by liujingxing** [comment]
把`open class ResponseParser<T> : AbstractParser<T>`
改为`open class ResponseParser<T> : AbstractParser<Response<T>>`,此时toResponse方法就会返回整个`Response`对象

**Comment by NeVaDaAAA** [comment]
好的 谢谢你 解决了我的问题
