### ISSUE TITLE
突然找不到DiskLruCache.create方法

### ISSUE THREAD

**Issue by harryhasai** [liujingxing/okhttp-RxHttp#117]
![image](https://user-images.githubusercontent.com/28555314/85489166-2da1f500-b602-11ea-9789-80b47c90a678.png)
![image](https://user-images.githubusercontent.com/28555314/85489235-4ad6c380-b602-11ea-92d1-3ca5c51e351d.png)
麻烦大佬 , 找了半天问题没有找到

**Comment by liujingxing** [comment]
你依赖的okhttp版本，跟告诉rxhttp的okhttp版本不一致

**Comment by harryhasai** [comment]
![image](https://user-images.githubusercontent.com/28555314/85489647-e1a38000-b602-11ea-97c7-270f266dafaa.png)
![image](https://user-images.githubusercontent.com/28555314/85489719-ff70e500-b602-11ea-904d-1a53e163c992.png)
应该是没问题的, 那应该是别的库里的包含的okhttp冲突了?

**Comment by harryhasai** [comment]
请问如果是冲突 有什么好的解决办法吗?

**Comment by liujingxing** [comment]
你依赖的okhttp版本号跟第三方依赖的保持一致；或者剔除第三方依赖的okhttp

**Comment by liujingxing** [comment]
rxhttp 已经适配了 okhtttp  3.12.0 - 4.7.2 （除过4.3.0版本）中的任一版本。

**Comment by harryhasai** [comment]
感谢大佬解惑!!!! 谢谢
