### ISSUE TITLE
能加一个更新OkHttpClient的方法吗。。

### ISSUE THREAD

**Issue by xyggs** [liujingxing/okhttp-RxHttp#121]

**Comment by liujingxing** [comment]
？？？什么意思？什么需求？

**Comment by xyggs** [comment]
val ok = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .readTimeout(10, TimeUnit.SECONDS)
            .writeTimeout(10, TimeUnit.SECONDS)
            .addInterceptor(ParamsInterceptor.Builder().build())
        .build()

        RxHttp.setDebug(BuildConfig.DEBUG)
        RxHttp.init(ok)

我在这儿的ok   设置了 ParamsInterceptor 这个拦截器   但是我想在某个请求 不使用这个 拦截器了，， 就想重新设置个OkHttpClient， 但是我看只能 通过init 来设置 又只允许设置一次

**Comment by liujingxing** [comment]
使用`@OkClient`注解，为不同请求指定不同的OkHttpCient对象，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#okclient

**Comment by xyggs** [comment]
额   谢谢大佬  没看到这儿来
