### ISSUE TITLE
同步返回网络响应

### ISSUE THREAD

**Issue by inshyma** [liujingxing/okhttp-RxHttp#130]
现有的方法实现同步返回响应么?

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%8C%87%E5%AE%9A%E8%AF%B7%E6%B1%82%E3%80%81%E5%9B%9E%E8%B0%83%E7%BA%BF%E7%A8%8B

**Comment by inshyma** [comment]
你的意思是:  执行  .subscribeOnCurrent() ...方法     那.subscribe() 是你重写了方法么? 我记得.subscribe()返回的是Disposable对象

**Comment by liujingxing** [comment]
`subscribe()`方法都是返回`Disposable`对象的，只是调用`subscribeOnCurrent()`方法后，请求就变成同步了，在回调里就可以拿到返回值，这种是通过回调的同步；如果你想要通过返回值式的同步，可以使用`RxHttp#execute`方法。
