### ISSUE TITLE
请问如何用协程与你的这个网络请求框架实现多并发请求同时发起然后统一处理回调的业务

### ISSUE THREAD

**Issue by sweet2o09** [liujingxing/okhttp-RxHttp#131]
请问如何用协程与你的这个网络请求框架实现多并发请求同时发起然后统一处理回调的业务

**Comment by liujingxing** [comment]
看这里https://juejin.im/post/5e77604fe51d4527066eb81a#heading-17

**Comment by sweet2o09** [comment]
好的,十分感谢,还有一个业务场景想要请教一下
现在app一版都有个token,token都是有时效性的,假如token失效了,我们需要去调用一个刷新token的接口,然后把新token放到原有的请求里面重新发送,这种场景的话要如何使用你的这个框架?

**Comment by liujingxing** [comment]
看Demo的TokenInterceptor类
