### ISSUE TITLE
请问一下，现在可以支持文件断点续上传吗？

### ISSUE THREAD

**Issue by zfl541091999** [liujingxing/okhttp-RxHttp#132]
rxhttp框架的确非常好用，看了一下wiki，有断点下载功能，不知道是否有断点续传功能，感谢大大

**Comment by liujingxing** [comment]
断点续传更多的工作量在服务端，需要服务端记录断点位置，客户端上传前获取断点位置，并从断点位置开始上传，目前你可通过自定义Param自行实现

**Comment by zfl541091999** [comment]
> 断点续传更多的工作量在服务端，需要服务端记录断点位置，客户端上传前获取断点位置，并从断点位置开始上传，目前你可通过自定义Param自行实现

请问用setRangeHeader(length, true) 可以实现我想要的断点续传功能吗？如果不行的话我就看看怎么使用那个自定义Param，非常感谢回答

**Comment by liujingxing** [comment]
setRangeHeader(length, true)是用于客户端告诉服务器请求范围的

自定义Param看这里 https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param

断点上传可以参考这个https://www.cnblogs.com/handsometong/p/6209386.html

**Comment by zfl541091999** [comment]
> setRangeHeader(length, true)是用于客户端告诉服务器请求范围的
> 
> 自定义Param看这里 https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param
> 
> 断点上传可以参考这个https://www.cnblogs.com/handsometong/p/6209386.html

非常感谢
