### ISSUE TITLE
lifeOnMain

### ISSUE THREAD

**Issue by Liangwenb** [liujingxing/okhttp-RxHttp#134]
` .doOnSubscribe {  iView?.showLoad() }.doFinally {iView?.hideLoad()} .lifeOnMain(this)
   .subscribe `

.lifeOnMain(this)是不是不等价于.subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())  doOnSubscribe和doFinally之类的方法还是在子线程中呢

**Comment by liujingxing** [comment]
lifeOnMain 只会做两件事，绑定页面声明周期，并控制下游线程；RxHttp默认在IO线程执行请求，也默认在IO线程回调
