### ISSUE TITLE
请求走成功也走失败方法，越界异常

### ISSUE THREAD

**Issue by matianbo** [liujingxing/okhttp-RxHttp#136]
我们服务器返回的data中有两个数组，当其中一个为空的时候，会出现这种情况，出现越界异常错误，怎么解决呢

**Comment by liujingxing** [comment]
更改下解析器里抛异常的判断逻辑就好了

**Comment by matianbo** [comment]
@SuppressWarnings("unchecked")
    @Override
    public T onParse(@NotNull okhttp3.Response response) throws IOException {
        final Type type = ParameterizedTypeImpl.get(Response.class, mType); //获取泛型类型
        Response<T> data = convert(response, type);
        T t = data.getData(); //获取data字段
        if (t == null && mType == String.class) {
            /*
             * 考虑到有些时候服务端会返回：{"errorCode":0,"errorMsg":"关注成功"}  类似没有data的数据
             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
             */
            t = (T) data.getMsg();
        }
        if (data.getCode() != 0 || t == null) {//code不等于0，说明数据不正确，抛出异常
            throw new ParseException(String.valueOf(data.getCode()), data.getMsg(), response);
        }
        return t;
    }
}
是在这里修改么，因为我返回的两个集合其中一个有时候需要为空，这里该怎么处理呢

**Comment by liujingxing** [comment]
仔细想了一下，RxHttp内部不会抛出数组越界异常，应该是你在成功回调里出现的异常，自己再排查下。如果成功回调出现异常，接着就会走失败回调。

**Comment by matianbo** [comment]
我感觉是成功回调出现了异常，毕竟也走成功的回调了，但是这块我得在哪里能处理呢

**Comment by liujingxing** [comment]
成功回调里，出现数组越界的地方判断下不就好了？

**Comment by matianbo** [comment]
这个问题是昨天遇到的，明天看看
