### ISSUE TITLE
错误: 找不到符号 Type tTypeList = ParameterizedTypeImpl.get(List.class, type);

### ISSUE THREAD

**Issue by benxin123** [liujingxing/okhttp-RxHttp#137]
kapt 'com.ljx.rxhttp:rxhttp-compiler:2.3.1'
错误: 找不到符号
Type tTypeList = ParameterizedTypeImpl.get(List.class, type);
^
符号: 类 Type
位置: 类 RxHttp<P,R>
其中, P,R是类型变量:
P扩展已在类 RxHttp中声明的Param
R扩展已在类 RxHttp中声明的RxHttp

kapt 'com.ljx.rxhttp:rxhttp-compiler:2.2.8'
就不会有这个提示

**Comment by GodFan4** [comment]
+1

**Comment by CrazyDoraemon** [comment]
+1

**Comment by liujingxing** [comment]
翻车了，请更新至v2.3.2版本
