### ISSUE TITLE
拦截器添加请求头无效

### ISSUE THREAD

**Issue by Ye83** [liujingxing/okhttp-RxHttp#142]
![image](https://user-images.githubusercontent.com/17722346/89874945-2a34ee00-dbef-11ea-906e-09d91b995059.png)
![image](https://user-images.githubusercontent.com/17722346/89875006-4173db80-dbef-11ea-8795-1cf488ec9f1b.png)
![image](https://user-images.githubusercontent.com/17722346/89875046-4f296100-dbef-11ea-933f-f1b1162ec691.png)
在拦截器添加请求头没效，没有加进请求头上

**Comment by Ye83** [comment]
调用的是RxHttp.postJson

**Comment by liujingxing** [comment]
是拦截器里的`intercept` 方法没回调？
我看你`MyApplication.getInstance().getToken`代码打上了双引号，确定没写错？
你是如何确定没添加进请求头的？通过RxHttp自定的日志打印？RxHttp的日志打印在拦截器回调前，故拦截器里添加的请求头，日志是不会打印的。

**Comment by Ye83** [comment]
解决了，谢谢

**Comment by Ye83** [comment]
问题已经解决
