### ISSUE TITLE
出现解析失败问题JsonSyntaxException如何处理

### ISSUE THREAD

**Issue by matianbo12345** [liujingxing/okhttp-RxHttp#143]
服务器给返回的数据为
{
	"code": 1,
	"msg": "用户名不存在或者密码错误",
	"data": "请求失败"
}
直接跑这个异常
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 40 path $.data

**Comment by liujingxing** [comment]
这种情况是服务器返回的数据不规范，data字段应该是个对象，却返回个字符串，导致解析失败；
最有的解决方案是叫服务端改，服务端不愿意改那客户端就要分两次解析，具体看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8

**Comment by matianbo12345** [comment]
好的谢谢
