### ISSUE TITLE
upload的时候无法添加参数

### ISSUE THREAD

**Issue by thisnameisused** [liujingxing/okhttp-RxHttp#145]
upload的时候无法添加参数，请求后参数没有带过去

**Comment by thisnameisused** [comment]
是需要json头的文件上传。。form的不行，能支持么

**Comment by liujingxing** [comment]
只有表单请求才支持上传文件；当然，如果你的文件是图片，可以将图片转base64字符串，然后以json字符串的形式上传。

你说的无法添加参数是什么意思？贴下代码看看。

**Comment by thisnameisused** [comment]
> 只有表单请求才支持上传文件；当然，如果你的文件是图片，可以将图片转base64字符串，然后以json字符串的形式上传。
> 
> 你说的无法添加参数是什么意思？贴下代码看看。

![1](https://user-images.githubusercontent.com/19217047/90631956-30ae1000-e256-11ea-997c-6ee9a6463f8e.png)
![2](https://user-images.githubusercontent.com/19217047/90631962-33106a00-e256-11ea-9b62-04b25ad69071.png)
第一个图是fiddler抓的包，用retrofit上传携带的参数
第二个图是fiddler抓的包，用rxhttp上传携带的参数
第二种服务器不认，但是又无法添加第一种参数
![3](https://user-images.githubusercontent.com/19217047/90632107-736fe800-e256-11ea-8e93-49c24cb5ead1.png)

**Comment by liujingxing** [comment]
都是表单请求，肯定哪里不一样，构建`upFile`对象代码及retrofit构建`RequestBody`的代码贴下

**Comment by thisnameisused** [comment]
> 都是表单请求，肯定哪里不一样，构建`upFile`对象代码及retrofit构建`RequestBody`的代码贴下

您好 这个issue close掉吧，最开始我是在parse那里试图从request.body里面取出携带过去的参数，发现无法获取到，误以为没有携带过去，fiddler抓包后参数发现已经带过去，只是参数没有content-type：json，以为格式不一样，但其实效果是一样的。

**Comment by liujingxing** [comment]
好的，有问题及时反馈，
