### ISSUE TITLE
单个请求可单独设置OkHttpClient吗

### ISSUE THREAD

**Issue by 867588763** [liujingxing/okhttp-RxHttp#151]
单个请求可单独设置OkHttpClient吗

**Comment by liujingxing** [comment]
当然可以，而且十分优雅，使用`@OkClient`注解即可，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#okclient

**Comment by 867588763** [comment]
确实比较优雅，还有一个问题可以通过tag 来取消网络请求吗。一个页面上可能有多个网络请求，通过设置相同的tag 来取消当前页面的所有请求

**Comment by liujingxing** [comment]
支持，通过`tag(Object)`方法打tag，通过`RxHttpPlugins.cancel(Object)`方法关闭

**Comment by 867588763** [comment]
欧克，感谢大佬
