### ISSUE TITLE
请求回调设置AndroidSchedulers.mainThread() 无效

### ISSUE THREAD

**Issue by 867588763** [liujingxing/okhttp-RxHttp#153]
![微信图片_20200904162045](https://user-images.githubusercontent.com/17881190/92217768-bbd00c80-eeca-11ea-9f9b-0a2ec15a69f6.png)

**Comment by liujingxing** [comment]
这样肯定无效啊，你要拿到`observeon`的返回值去订阅事件才有效，用链式调用就好了。

**Comment by 867588763** [comment]
大意了，这个对象还是之前的

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/92218527-d6ef4c00-eecb-11ea-8e40-222801112070.png)

**Comment by 867588763** [comment]
解决了，项目模块多，又封装了一层做网络库
