### ISSUE TITLE
有提供aar 包吗

### ISSUE THREAD

**Issue by 867588763** [liujingxing/okhttp-RxHttp#154]

**Comment by liujingxing** [comment]
没有，为啥不用远程依赖？

**Comment by 867588763** [comment]
要弄个aar 包给其他项目使用，里面包括了这个rxhttp

**Comment by liujingxing** [comment]
远程依赖下载下载，本地就用aar 包了，在/.gradle/caches/modules-2/files-2.1/com.ljx.rxhttp/rxhttp目录下可以找到

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/92342630-f49efa00-f0f3-11ea-8fc6-ff11261f3aad.png)
找到了，依赖挺多的，感谢

**Comment by liujingxing** [comment]
converter是非必须的，按自己需求选择即可。
