### ISSUE TITLE
postJson 接受服务器返回的json结果有错误

### ISSUE THREAD

**Issue by 867588763** [liujingxing/okhttp-RxHttp#156]
![image](https://user-images.githubusercontent.com/17881190/93036383-4dc9d900-f672-11ea-9ca6-f60f37054a16.png)

![image](https://user-images.githubusercontent.com/17881190/93036538-bdd85f00-f672-11ea-80bc-1fe39715b912.png)

OKHttp 原始请求方式 是能接受到

![image](https://user-images.githubusercontent.com/17881190/93036512-a8fbcb80-f672-11ea-9481-9aa22da91788.png)

**Comment by 867588763** [comment]
下面是OKHTTP 原始请求服务器返回的json
![image](https://user-images.githubusercontent.com/17881190/93036579-dcd6f100-f672-11ea-90d3-683981f21b79.png)

**Comment by liujingxing** [comment]
不要手动添加content-type，postJson默认就是application/json

**Comment by liujingxing** [comment]
还有，请注意一个地方，你用okhttp发送请求，返回的http状态码一样是400

**Comment by 867588763** [comment]
我去掉了content-type ,还是拿不到 服务器返回的json  一直返回Bad Request

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93040491-b8801200-f67c-11ea-8a84-a1d041c260e1.png)

**Comment by liujingxing** [comment]
那就是你接口的问题，自己先用postman调通

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93043406-3dbaf500-f684-11ea-888e-bf34cbbb2c8e.png)


服务器返回400     public <T> T convert(ResponseBody body, @NonNull Type type, boolean needDecodeResult) 这个方法没走

**Comment by 867588763** [comment]
进不到我自定义的转化器里面去

**Comment by liujingxing** [comment]
都400了，肯定不走，走了有啥意义？

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93045080-dc495500-f688-11ea-9d45-0c89a225d916.png)
![image](https://user-images.githubusercontent.com/17881190/93045187-161a5b80-f689-11ea-8a13-fcf9a94b6f89.png)

 这个类型应该是json  

下面是OKHTTP,能拿到json
![image](https://user-images.githubusercontent.com/17881190/93045266-49f58100-f689-11ea-8832-34d4e5b38523.png)

**Comment by liujingxing** [comment]
`RxHttp.setDebug(true)`开启调试模式，过滤RxHttp，把请求日志截图出来吧

**Comment by liujingxing** [comment]
大概知道问题，你自定义coverter里面的MediaType 格式不对，应该是：`application/json; charset=UTF-8`，而你的是`application/json;charset=UTF-8`  中间少了空格。

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93047412-0736a780-f68f-11ea-92ed-ff772dce4f9b.png)

**Comment by 867588763** [comment]
GsonConverter 自定义我是拷贝的rxhttp 里面的

**Comment by 867588763** [comment]
想看看是不是转换器的问题

**Comment by liujingxing** [comment]
RxHttp内部的GsonConverter是有空格的；请求结束日志也贴出来。

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93047728-b07d9d80-f68f-11ea-871f-bf473226e197.png)

**Comment by liujingxing** [comment]
你用okhttp时，content-type带上编码格式试试，即：`application/json; charset=UTF-8`别忘记空格

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93048031-7a8ce900-f690-11ea-9fea-225c67b2a508.png)

**Comment by 867588763** [comment]
networkResponse 这个body里面 类型不知道怎么就变成了text

**Comment by liujingxing** [comment]
我看你用RxHttp发请求是，请求头有重复的，去重后再试试，再不行，加我QQ 327744707

**Comment by 867588763** [comment]
![image](https://user-images.githubusercontent.com/17881190/93048995-b32dc200-f692-11ea-94e2-41f336f75b94.png)
加了

**Comment by 867588763** [comment]
解决了，公共请求头和单个请求头重复了
