### ISSUE TITLE
上传String类型的文本加密字符串

### ISSUE THREAD

**Issue by 867588763** [liujingxing/okhttp-RxHttp#159]
支持上传String类型的文本吗

**Comment by 867588763** [comment]
有一个Post接口数据是json的，但是加密过后就是一串字符串
![image](https://user-images.githubusercontent.com/17881190/93419088-6f2efd00-f8de-11ea-894a-568113caa049.png)
这个方法会报错

**Comment by liujingxing** [comment]
加密请求，请查看自定义Param   https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param
