### ISSUE TITLE
给GsonConverter暴露个接口自定义type adapter吧

### ISSUE THREAD

**Issue by zkywalker** [liujingxing/okhttp-RxHttp#162]
或者加下”“这样的空字符串也算做null类型，丢失精度的数字强转其实也可以加一下。
总有【口吐芬芳】的【屏蔽】后端瞎【打码】返回数据。

**Comment by liujingxing** [comment]
可以通过`RxHttpPlugins.setConverter(IConverter)`设置全局的转换器，对于内置的`GsonConverter`也支持自定义`Gson`，如`GsonConverter.create(new Gson())`
