### ISSUE TITLE
token 问题

### ISSUE THREAD

**Issue by honganxue** [liujingxing/okhttp-RxHttp#164]
请问如何添加头部token?   我看了你配置公共参数是在Application 中执行，  但是token 是在登录后才获取到 后面接口访问都要携带token 在头部请问怎么添加？

**Comment by liujingxing** [comment]
`RxHttp.setOnParamAssembly`设置的公共参数回调，在每次发起请求都会被执行，判断下，有就添加，没有不添加就好了。

**Comment by jackandroid2016** [comment]
自动刷新token呢

**Comment by jackandroid2016** [comment]
我可以通过拦截器处理吗

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/blob/master/app/src/main/java/com/example/httpsender/interceptor/RedirectInterceptor.java
