### ISSUE TITLE
kotlin DefaultDomain 提示不是public

### ISSUE THREAD

**Issue by thisnameisused** [liujingxing/okhttp-RxHttp#165]
已经增加public修饰符（默认就是public，但是显示加上也不行）

**Comment by liujingxing** [comment]
Kotlin编写的类需要带上`@JvmField`注解，详情查看https://github.com/liujingxing/okhttp-RxHttp/blob/50a16b20302b04df09b87662806e4c07dcd3d783/app/src/main/java/com/example/httpsender/entity/Url.kt

**Comment by thisnameisused** [comment]
谢谢
