### ISSUE TITLE
生成了RxHttp类，却没有asXxx方法

### ISSUE THREAD

**Issue by wangsong1991** [liujingxing/okhttp-RxHttp#169]
按照文档来还是不能生成asXxx方法，另一个项目里面就没有问题，新写的demo就导入不了

**Comment by wangsong1991** [comment]
versions.android_gradle_plugin = "3.6.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
这个版本 就是依赖不上，新建项目一样的方法导入，就可以导入成功，能给个解决方法吗

**Comment by liujingxing** [comment]
> 按照文档来还是不能生成asXxx方法，另一个项目里面就没有问题，新写的demo就导入不了

RxHttp 2.2.2版本起，需要手动依赖RxJava，并告诉RxHttp依赖的RxJava版本，如下：
```
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                    //必须，告知RxHttp你依赖的okhttp版本，目前已适配 v3.12.0 - v4.9.0版本  (v4.3.0除外)
                    rxhttp_okhttp: '4.9.0'，
                    //使用asXxx方法时必须，告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
                    rxhttp_rxjava: 'rxjava3'， 
                    rxhttp_package: 'rxhttp'   //非必须，指定RxHttp类包名
                ]
            }
        }
    }
```

**Comment by liujingxing** [comment]
> versions.android_gradle_plugin = "3.6.1"
> distributionUrl=https://services.gradle.org/distributions/gradle-5.6.4-all.zip
> 这个版本 就是依赖不上，新建项目一样的方法导入，就可以导入成功，能给个解决方法吗

依赖rxhttp哪个版本？

**Comment by Ekhui** [comment]
新版的studio好像rebuild不出RxHttp类 我原来的项目报红 下载的demo或者重新建立一个项目也报红

**Comment by liujingxing** [comment]
> 新版的studio好像rebuild不出RxHttp类 我原来的项目报红 下载的demo或者重新建立一个项目也报红 @liujingxing

新版是哪个版本，我自己的Android studio 4.1版本，没有问题，RxHttp类无法生成，看这里，按步骤检查https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#1首次集成rxhttp却没有rxhttp这个类

**Comment by liujingxing** [comment]
[文档已更新，100%解决，RxHttp无法生成问题](https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#1首次集成rxhttp却没有rxhttp这个类)
