### ISSUE TITLE
可以的话，能否将RxJava的demo和Kt的demo分一下

### ISSUE THREAD

**Issue by Reginer** [liujingxing/okhttp-RxHttp#170]
也好在代码里明确下各自单独的配置

**Comment by Reginer** [comment]
分成两个模块

**Comment by liujingxing** [comment]
这个很抱歉，分开容易，但维护起来就更费劲了，Demo后续都会使用kotlin编写；至于具体如何配置，文档里都有写。

**Comment by Reginer** [comment]
如果是这样的话，可否在几个类公用的时候，简单地注释下kt和java的区别。
比如@Parser(name = "Response", wrappers = [MutableList::class])，那个wrappers，协程可以不写的

**Comment by liujingxing** [comment]
这个可以有，感谢提醒
