### ISSUE TITLE
RxHttp这个类无法生成

### ISSUE THREAD

**Issue by mrcoderzou** [liujingxing/okhttp-RxHttp#171]
无论是Java项目还是Kotlin项目，按照文档配置之后都无法生成RxHttp这个类，甚至把源码下载下来运行也无法生成。
AS版本4.1

build.gradle配置如下：

apply plugin: 'com.android.application'
//java和kotlin混合开发需要用引入
apply plugin: 'kotlin-android'
//使用kapt依赖rxhttp-compiler，需要导入kapt插件
apply plugin: 'kotlin-kapt'
//省去findviewbyid
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.cnpc.rxhttpdemo"
        minSdkVersion 14
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        //必须，告知RxHttp你依赖的okhttp版本，目前已适配 v3.12.0 - v4.8.1版本
                        rxhttp_okhttp: '4.8.1',
                        //使用asXxx方法时必须，告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
                        rxhttp_rxjava: 'rxjava3',
                        rxhttp_package: 'rxhttp'   //非必须，指定RxHttp相关类的生成路径，即包名
                ]
            }
        }
    }

    //必须，java 8或更高
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    //以下3个为必须，
    implementation 'com.ljx.rxhttp:rxhttp:2.3.5'
    implementation 'com.squareup.okhttp3:okhttp:4.8.1' //rxhttp v2.2.2版本起，需要手动依赖okhttp
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.3.5' //生成RxHttp类，非kotlin项目，请使用annotationProcessor代替kapt

    //rxjava3
    implementation 'io.reactivex.rxjava3:rxjava:3.0.2'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.ljx.rxlife3:rxlife-rxjava:3.0.0' //管理RxJava3生命周期，页面销毁，关闭请求

}

**Comment by liujingxing** [comment]
kotlin项目使用kapt替代annotationProcessor，如果还无法生成，进QQ群跟我联系378530627

**Comment by yangdengxueshi** [comment]
点击菜单 Build -> Rebuild Project

**Comment by liujingxing** [comment]
文档已更新，RxHttp类无法生成看这里，100%解决https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#1首次集成rxhttp却没有rxhttp这个类
