### ISSUE TITLE
上传时，文件过大内部抛出异常

### ISSUE THREAD

**Issue by dengyiqian** [liujingxing/okhttp-RxHttp#173]
![QQ图片20201026134305](https://user-images.githubusercontent.com/5867187/97137783-3a3d8200-1789-11eb-928e-3fad50b9d0fc.png)
![QQ图片20201026134318](https://user-images.githubusercontent.com/5867187/97137797-40336300-1789-11eb-9ced-65c957e51300.png)

**Comment by liujingxing** [comment]
这是上传的文件大小超过的最大限制导致的，客户端不会对上传的文件做任何限制，服务端会有最大限制，具体多少，请询问服务端开发人员。
