### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#174]
Rxhttp 请求报错 403 forbidden 怎么解决

**Comment by liujingxing** [comment]
这个要找你的服务端去问问

**Comment by chenyinchao** [comment]
> 这个要找你的服务端去问问

我发现是token过期了才报403 forbidden ，这个在rxhttp上怎么配置呀

**Comment by liujingxing** [comment]
过期就刷新token，看这里https://github.com/liujingxing/okhttp-RxHttp/issues/164

**Comment by chenyinchao** [comment]
> 过期就刷新 token，看这里#164

好滴，感谢
