### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by 283006603** [liujingxing/okhttp-RxHttp#175]
iCookieJar.saveCookie(httpUrl,cookie);这行调用不到API

**Comment by liujingxing** [comment]
估计你用法不对，可以看看这个 https://github.com/liujingxing/okhttp-RxHttp/issues/172

**Comment by liujingxing** [comment]
过期就刷新token，看这里https://github.com/liujingxing/okhttp-RxHttp/issues/164
