### ISSUE TITLE
Kotlin 中使用 RxLife 问题

### ISSUE THREAD

**Issue by liuqiangdd** [liujingxing/okhttp-RxHttp#177]
您好：
我在用 Kotlin 的一个 object 类中使用 RxLife 报错，请问我这么写有问题吗？如果有问题应该怎么写呢？谢谢！

None of the following functions can be called with the arguments supplied.

`object MoRequest {

    fun get(url: String, params: MoHttpParams? = null, callback: MoCallback) {
        val mapParams: MutableMap<String, Any>? = params?.map() ?: mutableMapOf()
        RxHttp.get(url).addAll(mapParams).asString().to(RxLife.toMain(this)).subscribe({ s ->
            callback.onSuccess(s)
        }) { t ->
            callback.onFail(t.message)
        }
    }
}
`

**Comment by liujingxing** [comment]
看RxLife文档https://github.com/liujingxing/rxjava-RxLife
