### ISSUE TITLE
put方式上传视频文件有问题

### ISSUE THREAD

**Issue by dengyiqian** [liujingxing/okhttp-RxHttp#179]
我通过put方式上传MP4之后，服务器会给我返回一个视频地址，这个地址我放在浏览器不能正常播放，
解决方式，需要继承FormParam类，重新构造RequestBody类，指定MediaType，然后在上传，这个时候服务器返回的视频地址就能在浏览器正常播放了

**Comment by liujingxing** [comment]
`RxHttp v2.5.2`新增了`BodyParam`，可通过
```java
RxHttp.putBody("/service/...")
       .setBody(File)
       ...
```
更好的解决你遇到的问题

**Comment by LnLooFa** [comment]
通过putBody 怎么把Content-Type设置为空,我添加了addHeader("Content-Type", "")或者setHeader("Content-Type", "")  抓包的时候都是带有Content-Type 类型,,我需要上传图片,,需要把这个类型设置为空

**Comment by liujingxing** [comment]
@LnLooFa 把文件转ResponseBody对象，随后调用以下代码发送请求
` ` `java
RxHttp.postBody("")
    .setBody(body)
    ....
` ` `

**Comment by LnLooFa** [comment]
@liujingxing 谢谢指点,,成功了,问题已解决,应该是RequestBody
