### ISSUE TITLE
最近准备替换Retrofit，有些用法需要咨询下

### ISSUE THREAD

**Issue by qiushui95** [liujingxing/okhttp-RxHttp#182]
谢答！
```
@JsonQualifier
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class ResponseResult
```

```
    @ResponseResult
    @POST("***/***/***/***")
    suspend fun postCallRecord(
        @Body callList: List<CallRecordRequest>
    ): CallRecordPushResponseContainer
```
如上，我使用的是Moshi解析，在定义接口的时候加了ResponseResult注解，解析json的时候moshi会得到该注解进行特殊操作，RxHttp应该把该注解加在什么地方

**Comment by liujingxing** [comment]
很抱歉，这个暂时还不支持，后续会想办法兼容

**Comment by qiushui95** [comment]
@liujingxing 库很好，也很吸引我，但目前这个困扰还是挺大的。谢答，谢开源

**Comment by liujingxing** [comment]
会尽快兼容，感谢提出

**Comment by liujingxing** [comment]
方便的话，加下我QQ，327744707

**Comment by liujingxing** [comment]
经过慎重考虑，暂时不打算兼容这种情况（改动太大，得不偿失），该场景亦可通过[自定义解析器](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)去替代，可返回任意数据类型，且实现更加简单，感谢提出。
