### ISSUE TITLE
Could not find rxhttp-compiler-2.4.2.ja

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/okhttp-RxHttp#183]
> Task :app:javaPreCompileDevDebug FAILED

Execution failed for task ':app:javaPreCompileDevDebug'.
> Could not resolve all files for configuration ':app:devDebugAnnotationProcessorClasspath'.
   > Could not find rxhttp-compiler-2.4.2.jar (com.ljx.rxhttp:rxhttp-compiler:2.4.2).
     Searched in the following locations:
         http://maven.aliyun.com/nexus/content/repositories/jcenter/com/ljx/rxhttp/rxhttp-compiler/2.4.2/rxhttp-compiler-2.4.2.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by liujingxing** [comment]
你开了代理，导致下载地址不对
