### ISSUE TITLE
> Task :app:compileDevDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/okhttp-RxHttp#184]
> Task :app:compileDevDebugJavaWithJavac FAILED
Make sure all annotation processors are incremental to improve your build speed.
import rxhttp.wrapper.param.RxHttp;
   
import rxhttp.wrapper.param.RxHttp;
                           ^
  符号:   类 RxHttp
  位置: 程序包 rxhttp.wrapper.param

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 657ms
37 actionable tasks: 2 executed, 35 up-to-date

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#2android-studio提示rxhttp类找不到
