### ISSUE TITLE
关于下载进度回调问题

### ISSUE THREAD

**Issue by xygaozhizhi** [liujingxing/okhttp-RxHttp#189]
大佬您好，#188issues那个问题，没有办法确定文件总大小，有没有办法支持回调文件当前已经下载的大小呢？

**Comment by liujingxing** [comment]
你是想进度回调里 ，progress、totalSize返回0，然后currentSize返回当前已下载的字节数？

**Comment by xygaozhizhi** [comment]
嗯，这样的话后台返回个文件总大小字段也算是能满足需求。另外如果想显示下载速度应该怎么处理呢？毕竟下载速度和当前网速不是一回事

**Comment by liujingxing** [comment]
等版本更新吧。至于下载速度，这个没有，个人感觉意义不大。

**Comment by xygaozhizhi** [comment]
好的。不过现在大多APP中的文件下载都会有下载速度显示，下载速度是根据每秒接收到的字节数计算出来的，这东西应该是这么算的吧？

**Comment by liujingxing** [comment]
[RxHttp v2.5.1](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)版本 已兼容该情况
