### ISSUE TITLE
解析对象得到{}

### ISSUE THREAD

**Issue by 1843163412** [liujingxing/okhttp-RxHttp#190]
```kotlin
val pageList = RxHttp.get("zhjg/api/sys/process/no-read-count")
                .toClass<Response<ReadCountBean>>()
//                .setAssemblyEnabled(false)   //设置是否添加公共参数/头部，默认为true
//                .toResponse<List<ReadCountBean>>()
                .await()
        Log.e("----", "sendPostForm: " + Gson().toJson(pageList))
```

2020-11-19 10:43:07.199 30622-30670/com.liaoying.baseutils I/RxHttp: <------ rxhttp/2.4.3 okhttp/4.9.0 request end Method=GET Code=200 ------>(824ms)
    
    https://fwyz.mem.gov.cn:1088/zhjg/api/sys/process/no-read-count
    
    Server: Firewall
    Date: Thu, 19 Nov 2020 02:35:06 GMT
    Content-Type: application/json;charset=UTF-8
    Transfer-Encoding: chunked
    Connection: keep-alive
    
    {"status":true,"message":"操作成功","code":"00000","data":[]}
2020-11-19 10:43:07.272 30622-30622/com.liaoying.baseutils E/----: sendPostForm: {}

**Comment by liujingxing** [comment]
你希望的data是`ReadCountBean`对象，然而，服务器给你返回了数组，这样自然解析就失败了。[解决办法点这里](https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8)

**Comment by 1843163412** [comment]
demo里都可以返个[] 给我，但是我写的就不行

**Comment by 1843163412** [comment]
val pageList = RxHttp.get("zhjg/api/sys/process/no-read-count")
                .toResponse<List<ReadCountBean>>()
                .await()
 @Throws(IOException::class)
    override fun onParse(response: okhttp3.Response): T {
        val type: Type = ParameterizedTypeImpl[Response::class.java, mType] //获取泛型类型
        val data: Response<T> = response.convert(type)
        Log.e("----", "onParse: " + Gson().toJson(data))
        var t = data.data //获取data字段
        if (t == null && mType === String::class.java) {
            /*
             * 考虑到有些时候服务端会返回：{"errorCode":0,"errorMsg":"关注成功"}  类似没有data的数据
             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
             */
            @Suppress("UNCHECKED_CAST")
            t = data.message as T
        }
        if (data.code =="00000" || t == null) { //code不等于0，说明数据不正确，抛出异常
            throw ParseException(data.code.toString(), data.message, response)
        }
        return t
    }

2020-11-19 11:04:40.306 5372-5549/com.liaoying.baseutils I/RxHttp: <------ rxhttp/2.4.3 okhttp/4.9.0 request end Method=GET Code=200 ------>(354ms)
    
    https://fwyz.mem.gov.cn:1088/zhjg/api/sys/process/no-read-count
    
    Server: Firewall
    Date: Thu, 19 Nov 2020 02:56:39 GMT
    Content-Type: application/json;charset=UTF-8
    Transfer-Encoding: chunked
    Connection: keep-alive
    
    {"status":true,"message":"操作成功","code":"00000","data":[]}
2020-11-19 11:04:40.334 3222-4517/? W/MiuiPerfServiceClient: PSI: Memory Some|52|436677006330041
2020-11-19 11:04:40.355 5372-5549/com.liaoying.baseutils E/----: onParse: {}

**Comment by liujingxing** [comment]
想要数组，就应该`toClass<Response<List<ReadCountBean>>>()`，该代码的解析方式等价于`toResponse<List<ReadCountBean>>()`

**Comment by 1843163412** [comment]
问题原因是开启混淆的原因导致解析报错
