### ISSUE TITLE
没有找到setSync这个方法

### ISSUE THREAD

**Issue by wengooooo** [liujingxing/okhttp-RxHttp#191]
https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%8C%87%E5%AE%9A%E8%AF%B7%E6%B1%82%E3%80%81%E5%9B%9E%E8%B0%83%E7%BA%BF%E7%A8%8B

按照文档这么写，没有找到setSync

implementation 'com.ljx.rxhttp:rxhttp:2.4.0'
implementation 'com.squareup.okhttp3:okhttp:3.12.0'
annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.4.0'

**Comment by liujingxing** [comment]
我确认是有的，该方法就是2.4.0版本加入的，如果没有，那就是你没有依赖RxJava，该方法是RxJava专属
