### ISSUE TITLE
错误怎么回调处理

### ISSUE THREAD

**Issue by LinMaris** [liujingxing/okhttp-RxHttp#193]
//Student对象
val student = RxHttp.get("/service/...")
    .toClass<Student>()
    .await()

像这样请求到的数据, 如果请求出错在哪里处理呢, 

await方法中没有错误的处理, 在 RxJava 中还可以在订阅方法里回调

**Comment by LinMaris** [comment]
val testURL = "https://www.wanandroid.com/article/list/0/json"
val jsonResult = RxHttp.postJson(testURL).toStr().await()
println("jsonResult: ${jsonResult}")

要是能报个错还好办, 现在啥都不输出, 就离谱

**Comment by liujingxing** [comment]
看看这篇文章，你会豁然开朗，https://juejin.cn/post/6856550856796897287#heading-25，重点看`awaitResult、tryAwait`操作符及第4小节。
