### ISSUE TITLE
如何做到解耦？

### ISSUE THREAD

**Issue by Power-Android** [liujingxing/okhttp-RxHttp#194]
.as(RxLife.asOnMain(this)) //页面销毁、自动关闭请求 并且在主线程回调观察者
this为actiivity或fragment
我在使用MVVM时如何保证vm不去持有view层的引用？
我目前的做法是通过CompositeDisposable来做到解耦
我在baseactivity里将v和vm绑定了生命周期，并在vm里创建CompositeDisposable，
在onCleared方法里调用mCompositeDisposable.clear();去取消请求
请问还有别的方式可以不引用this可以绑定生命周期吗？

**Comment by Power-Android** [comment]
还有一个关于MVVM的问题想请教一下，  我在M层做网络请求 如果我需要用到loading的dialog，这时候如果我传入了activity的context就没办法做到解耦了，但是传入application的context貌似也不恰当，请问我该如何去加载这个loading弹窗？需要我在activity里的方法调用前去开启 在viewmodel的observicable回调里去取消弹窗吗？ 有没有更好的办法？

**Comment by liujingxing** [comment]
对于RxLife的用法，可以看这里https://github.com/liujingxing/rxjava-RxLife；对于loading弹窗的显示/销毁，一般做法是在ViewModel里写个LiveData变量，保存请求状态，然后在Activity/Fragment监听这个状态。

**Comment by Power-Android** [comment]
ok
