### ISSUE TITLE
本地存储信息

### ISSUE THREAD

**Issue by 1325679717** [liujingxing/okhttp-RxHttp#195]
本地存储方式会替换为数据库吗？一般除了进度还会存一些附加信息（例如电影信息等等）

**Comment by liujingxing** [comment]
我怎么看了一脸懵逼，确定没走错地方？没走错的话，你是想问缓存？

**Comment by 1325679717** [comment]
是的，不好意思 我表达的问题，缓存功能

**Comment by liujingxing** [comment]
直接说你的需求吧

**Comment by 1325679717** [comment]
我下载一部电影 需要把电影名字和简介等信息

**Comment by 1325679717** [comment]
public float fraction;                          //下载的进度，0-1
    public long totalSize;                          //总字节长度, byte
    public long currentSize;                        //本次下载的大小, byte
    public Serializable extra1;                     //额外的数据                                                        意思就是需要缓存这个额外数据 ，现在框架好像无法将额外数据一起缓存下来，不知道这样表达清楚不

**Comment by liujingxing** [comment]
你这`Serializable extra1`数据哪里来的？服务器返回的？缓存的意思是，将服务器返回的数据，在sd卡保存一份，下次没有网络就可以读取sd卡里保存的数据。

**Comment by 1325679717** [comment]
是的

**Comment by liujingxing** [comment]
服务器返回的数据都会保存的，你现在的问题是什么？

**Comment by 1325679717** [comment]
那打扰了，可能我还不会用吧

**Comment by liujingxing** [comment]
你看看缓存的文档吧https://github.com/liujingxing/okhttp-RxHttp/wiki/%E7%BC%93%E5%AD%98%E7%AD%96%E7%95%A5

**Comment by 1325679717** [comment]
恩恩 好的 多谢
