### ISSUE TITLE
协程 activity 页面生命周期及关闭页面取消网络请求如何处理

### ISSUE THREAD

**Issue by JohnDwang** [liujingxing/okhttp-RxHttp#199]
协程 activity 页面生命周期及关闭页面取消网络请求如何处理

**Comment by liujingxing** [comment]
使用[RxLifeScope](https://github.com/liujingxing/RxLife-Coroutine)开启协程，页面关闭，协程自动关闭，请求也会跟着关闭

**Comment by JohnDwang** [comment]
> 使用[RxLifeScope](https://github.com/liujingxing/RxLife-Coroutine)开启协程，页面关闭，协程自动关闭，请求也会跟着关闭

链式调用没有toResponse()这个 我自定义了不知道在那调用或者封装

**Comment by liujingxing** [comment]
toResponse/asResponse 方法是通过[@Parser](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)注解生产的

**Comment by JohnDwang** [comment]
> toResponse/asResponse 方法是通过[@Parser](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)注解生成的

你有没有QQ群 拉我一下 472099458

**Comment by liujingxing** [comment]
378530627  直接进就好
