### ISSUE TITLE
关于使用RxHttp的项目，ReBuild产生不了RxHttp类应该怎么办？

### ISSUE THREAD

**Issue by sunshineLay** [liujingxing/okhttp-RxHttp#200]
情况是，新建项目ReBuild可以产生RxHttp类。但是我在公司提交到Github仓库，再从家里pull下来之后就无法产生了。哪怕删除RxHttp依赖再次添加也没有办法ReBuild得到。希望可以指点一下，谢谢。

**Comment by liujingxing** [comment]
rebuild报什么错？

**Comment by sunshineLay** [comment]
没有报错，rebuild正常，我在你的常见问题中发现了常规排查方法，我先试试，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tmacsy"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 晚上8:52
收件人: "liujingxing/okhttp-RxHttp"<okhttp-RxHttp@noreply.github.com&gt;; 
抄送: "Android【刘安异】"<2491812016@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liujingxing/okhttp-RxHttp] 关于使用RxHttp的项目，ReBuild产生不了RxHttp类应该怎么办？ (#200)





 
rebuild报什么错？

**Comment by liujingxing** [comment]
行，有问题再联系

**Comment by sunshineLay** [comment]
已经解决，是Kotlin项目用了annotationProcessor，而没有用kapt。
