### ISSUE TITLE
提交RxHttp.postJson(url)..addAll("{}")时，后台做了强制限制必须得有请求体，但RxHttp做了处理，设置未Null了，怎么可以添加？

### ISSUE THREAD

**Issue by xb576150019** [liujingxing/okhttp-RxHttp#201]
提交RxHttp.postJson(url)..addAll("{}")时，后台做了强制限制必须得有请求体，但RxHttp做了处理，设置未Null（JsonParam类中mParam设置为空了）了，怎么可以添加？

**Comment by liujingxing** [comment]
要发送空对象`{}`给服务端，目前最有效的方法是添加一个null值，如下：
```java
RxHttp.postJosn("/service/...")
        .add("test", null)
        .asString()
        .subscribe()
```
此时发送给服务的对象应该是`{"test":null}`,但由于Gson默认会自动过滤`null`值，所以真实发给服务器的就是`{}`

至于`addAll("{}") `这种方式，下个版本会直接兼容。

**Comment by xb576150019** [comment]
好的，感谢大佬，我们也是这样做的。

**Comment by liujingxing** [comment]
[RxHttp v2.5.1](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)版本，已支持`addAll("{}") `方式，发送空对象`{}`给服务器
