### ISSUE TITLE
有个问题，我循环请求10个网络，我要等他们的结果都回来之后操作，我该怎么操作呢？老哥

### ISSUE THREAD

**Issue by liyanfei250** [liujingxing/okhttp-RxHttp#204]
有个问题，我循环请求10个网络，我要等他们的结果都回来之后操作，我该怎么操作呢？老哥

**Comment by liujingxing** [comment]
RxJava的话，可以考虑使用`zipIterable`操作符；协程的话，[参考5.2章节](https://juejin.cn/post/6844904100090347528#heading-17)

**Comment by liyanfei250** [comment]
有这个提示就够了，thanks
