### ISSUE TITLE
get请求URL不拼接baseurl突然就不行了

### ISSUE THREAD

**Issue by hongyan0319** [liujingxing/okhttp-RxHttp#206]
Method threw 'java.lang.IllegalArgumentException' exception. Cannot evaluate rxhttp.wrapper.param.NoBodyParam.toString()，只有地址传全部的才对

**Comment by liujingxing** [comment]
突然就不行了，肯定是改了东西，想想看改了啥？还有rxhttp内部没有这个错误，详细错误日志发出来看看。

**Comment by hongyan0319** [comment]
E/RxJava: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
E/RxJava: java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
 E/RxJava: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
 E/RxJava: java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
代码中也设置了
public class ApiManager {
    @DefaultDomain()
    public static String baseUrl = "http://192.168.1.1:6080/";
而且编译生成的文件也有使用baseUrl
 /**
   * 给Param设置默认域名(如何缺席的话)，此方法会在请求发起前，被RxHttp内部调用
   */
  private P addDefaultDomainIfAbsent(P param) {
    String newUrl = addDomainIfAbsent(param.getSimpleUrl(), ApiManager.baseUrl);
    param.setUrl(newUrl);
    return param;
  }

**Comment by liujingxing** [comment]
到`addDefaultDomainIfAbsent `方法打个断点调试下就知道了。

**Comment by hongyan0319** [comment]
项目是组件化的项目，模块多了就不行，超过9个就不行了，刚发现
Cannot find local variable 'param'
Method threw 'java.lang.IllegalArgumentException' exception. Cannot evaluate rxhttp.wrapper.param.NoBodyParam.toString()

**Comment by liujingxing** [comment]
这个跟几个module没关系，你是不是多个module都单独依赖了`rxhttp-compiler`?那这样每个module都会生成RxHttp类，这是不对的。

把注解和`rxhttp-compiler`放到base module，其它module依赖base module就好。

**Comment by hongyan0319** [comment]
就是按照你说的这样来做的

**Comment by hongyan0319** [comment]
其他组件少的时候没问题，多了就不行了

**Comment by liujingxing** [comment]
肯定不是组件多少的问题，你可以在查查，可以查查baseurl 是不是在某个时候被重新赋值了，并且赋值为空字符串
