### ISSUE TITLE
能不能去掉annotationProcessor

### ISSUE THREAD

**Issue by Lans** [liujingxing/okhttp-RxHttp#208]
每次都是间歇式出现与消失，很浪费时间。用你这个库是为了方便，现在搞得很复杂了。butterknife可以完全搞定，要不借鉴一下？

**Comment by liujingxing** [comment]
间歇式出现与消失？什么意思？很复杂又具体指哪里？butterknife也是通过annotationProcessor实现的。

**Comment by Lans** [comment]
之前那个，那是代码错误。我理解。但是他一直是红的，看着很别扭

**Comment by liujingxing** [comment]
哪里是一直是红色的？

**Comment by Lans** [comment]
Rxhttp这个一直是红的，运行还没问题

**Comment by Lans** [comment]
![Screen Shot 2021-01-04 at 11 29 21 AM](https://user-images.githubusercontent.com/16605722/103498541-1af55c00-4e80-11eb-8ed4-84769ddfcf59.png)

**Comment by liujingxing** [comment]
我猜你把build文件夹设为忽略了，检查下
<img src="https://github.com/liujingxing/RxHttp/blob/master/screen/ignore_build.png" width = "684" height = "430" />

将build文件夹移除忽略配置即可

**Comment by Lans** [comment]
![Screen Shot 2021-01-04 at 11 32 34 AM](https://user-images.githubusercontent.com/16605722/103498662-8ccda580-4e80-11eb-9cbb-b33d84eeb2c1.png)
并没有

**Comment by liujingxing** [comment]
加我QQ  327744707
