### ISSUE TITLE
下载文件时有小概率不回调 成功/失败

### ISSUE THREAD

**Issue by CeuiLiSA** [liujingxing/okhttp-RxHttp#209]
通过打印进度日志观察到，凡是进度能达到100%的，都可以正常回调onNext + doFinal。
如果出现明显异常，如文件无读写权限或者下载网址错误，也可以正常回调onError + doFinal
现在的问题是，有小概率下载到99% / 98% / 97%后就没下文了, 等很久进度也不会更新到100%，也不会走onNext， 不会走onError，直接回调doFinal。

**Comment by CeuiLiSA** [comment]
大批量下载小文件的时候，出现的频率比较高

**Comment by liujingxing** [comment]
rxhttp旧版本会有 100% 这个进度不回调问题，你用的是哪个版本？

**Comment by CeuiLiSA** [comment]
用的这个
`    implementation 'com.ljx.rxhttp:rxhttp:2.5.2'
    kapt 'com.ljx.rxhttp:rxhttp-compiler:2.5.2'`

**Comment by liujingxing** [comment]
这个版本不会的，你用的什么方式下载，协程还是RxJava，大批量是多大？

**Comment by CeuiLiSA** [comment]
`RxHttp.get(bean.getUrl())
                .addHeader(Params.MAP_KEY, Params.IMAGE_REFERER)
                .setRangeHeader(nonius, true)
                .asDownload(factory, AndroidSchedulers.mainThread(), new Consumer<Progress>() {
                    @Override
                    public void accept(Progress progress) {
                        
                    }
                })`

我是这样子下载的，复现率一般是两三百张图片会出现一次，这些图片都是两三百KB的图片，或者五六十kB

**Comment by CeuiLiSA** [comment]
我是这样子下载的，复现率一般是两三百张图片会出现一次，这些图片都是两三百KB的图片，或者五六十kB

RxHttp.get(bean.getUrl())
                .addHeader(Params.MAP_KEY, Params.IMAGE_REFERER)
                .setRangeHeader(nonius, true)
                .asDownload(factory, AndroidSchedulers.mainThread(), new Consumer<Progress>())

**Comment by liujingxing** [comment]
并发太高了，你自己要限制下，否则会有超时的情况出现，至于你说的这个问题，方便的话，写个Demo给我，我有空找找原因。

**Comment by CeuiLiSA** [comment]
好的，我把正在下载的数量设置成一个。然后在onFinal里面也做了判断，即便没回调失败和成功也会让后续队列继续下载。所以这个问题应该不大了

**Comment by liujingxing** [comment]
成功和失败，是一定会回调其中一个的，目前的并发量规则是okhttp的规则，单个域名下，最多64个任务同时执行，方便的话，还写个Demo给我，我有空找找原因，感谢。

**Comment by CeuiLiSA** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft.git

拉代码跑起来之后，游客账号登录，进去主页长按任意图片，批量下载，开始下载。
退出至主页侧滑栏，点进下载管理，即可观察到下载进度。

**Comment by liujingxing** [comment]
好的，有空我试试，感谢

**Comment by CeuiLiSA** [comment]
辛苦了大佬
