### ISSUE TITLE
This class EntityParser must declare 'public EntityParser(java.lang.reflect.Type)' 

### ISSUE THREAD

**Issue by kxs109** [liujingxing/okhttp-RxHttp#210]
```java
@Parser(name = "Entity")
public class EntityParser<T> extends AbstractParser<T> {
    public EntityParser(Class<T> type) {
        super(type);
    }

    protected EntityParser() {
    }

    @Override
    public T onParse(@NotNull Response response) throws IOException {
        Type type = ParameterizedTypeImpl.get(BaseEntity.class, mType); //获取泛型类型
        BaseEntity<T> data = convert(response, type);  //获取Response对象
        T t = data.getData();                             //获取data字段
        if (!data.getSuccess())
            throw new ParseException(String.valueOf(data.getCode()), data.getMsg(), response);
        if (data.getSuccess() && t == null)
            throw new EmptyException(String.valueOf(data.getCode()), data.getMsg(), response);
        return t;
    }
}
```

**Comment by liujingxing** [comment]
将有参的构造方法，参数类型改为Type类型

**Comment by kxs109** [comment]
谢谢大佬了。上面的那个编译问题好了，又出现了新的编译问题：


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by liujingxing** [comment]
往上翻看详细错误日志

**Comment by kxs109** [comment]
可能是这里吧，直接编译没有详细的报错信息，我用gradlew assembleDebug编译的
> Task :lib_netWork:compileDebugKotlin
w: lib_netWork\build\generated\source\kapt\debug\rxhttp\wrapper\param\RxHttp.kt: (76, 15): Unchecked cast: RxHttpAbstractBodyParam<P, R> to R
w: lib_netWork\src\main\java\com\leyye\networklib\utlis\RxHttpUtil.kt: (88, 33): Condition 'saltCookie != null' is always 'true'

**Comment by liujingxing** [comment]
rxhttp、rxhttp-compiler版本要统一
