### ISSUE TITLE
纯Java项目，能生成RxHttp类，但是在使用了add方法后，再也无法使用asResponse之类的方法了。

### ISSUE THREAD

**Issue by youngledo** [liujingxing/okhttp-RxHttp#211]
RxHttp.postForm("sanrenxing-auth/oauth/token")
                .add("username", username).add("password", password).as*
这里无法出现asResponse、asList之类的。我看add方法返回的是RxHttpFormParam，这个肯定没有as*之类的方法吧？

依赖如下：
```groovy
    implementation 'com.ljx.rxhttp:rxhttp:2.5.3'
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.5.3'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'
```

**Comment by liujingxing** [comment]
asXxx方法是通过RxJava实现的，需要你自行依赖RxJava，你在看下接入文档

**Comment by youngledo** [comment]
> asXxx方法是通过RxJava实现的，需要你自行依赖RxJava，你在看下接入文档

并不行的，我加了这两个，并且重新rebuild还是一样没有。

```
    implementation 'io.reactivex.rxjava2:rxjava:2.2.20'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
```

**Comment by liujingxing** [comment]
```
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                    //使用asXxx方法时必须，告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
                    rxhttp_rxjava: 'rxjava3'， 
                    rxhttp_package: 'rxhttp'   //非必须，指定RxHttp类包名
                ]
            }
        }
    }
}
```
rxhttp_rxjava 参数加上

**Comment by youngledo** [comment]
> javaCompileOptions {
>             annotationProcessorOptions {
>                 arguments = [
>                     //使用asXxx方法时必须，告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
>                     rxhttp_rxjava: 'rxjava3'， 
>                     rxhttp_package: 'rxhttp'   //非必须，指定RxHttp类包名
>                 ]
>             }
>         }

所以你这个文档写的还是有问题的。又说可选，结果又是必选。

**Comment by liujingxing** [comment]
太难了

**Comment by youngledo** [comment]
我发现还是没有asResponse(Class)方法，只有.asOkResponse()方法。这是我的依赖：
dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
    implementation 'com.blankj:utilcode:1.29.0'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.ljx.rxhttp:rxhttp:2.5.3'
    implementation 'com.ljx.rxlife2:rxlife-rxjava:2.0.0'
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.5.3'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'
    // 测试
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

我是版本不支持吗？

**Comment by youngledo** [comment]
这个asOkResponse其实是OkHttp的对象，我该如何能点出asResponse？
<img width="637" alt="屏幕截图 2021-01-17 000903" src="https://user-images.githubusercontent.com/68590897/104816985-7567c280-5859-11eb-87d9-6d98ed909638.png">

**Comment by liujingxing** [comment]
你看的哪里的文档？asResponse方法是通过自定义解析器生成的，看看这里 https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser

**Comment by youngledo** [comment]
> 冒昧问下，你看的哪里的文档？asResponse方法是通过自定义解析器生成的，看看这里 https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser

我看的是掘金上面的，介绍的很全面。这些难道不是RxHttp已经默认提供的吗，难道还要我再自定义解析器？我建议可以内置一些常用的解析器。

**Comment by liujingxing** [comment]
目前一系列asXxx方法，都是通过内置解析器实现的，而你要的asResponse方法，涉及到具体业余逻辑(如业余code统一判断)，所以需要自定义。
