### ISSUE TITLE
段点下载报：请求范围不符合要求

### ISSUE THREAD

**Issue by zj110306** [liujingxing/okhttp-RxHttp#215]

**Comment by liujingxing** [comment]
Http状态码416了解下，当你请求的范围超出了服务器接受范围就会报这个错；如断点下载时，你传入范围 1000000-结束，而服务器的文件小于等于1000000，就会报这个错误。一般的做法是，下载前对已下载的文件做md5校验，如果md5值能对上，就不再下载。

**Comment by zhenyea** [comment]
麻烦问下”你传入范围 1000000-结束“这个传入范围是哪个字段表示的？

**Comment by liujingxing** [comment]
`RANGE: bytes=1000000-` 代表1000000-结束
