### ISSUE TITLE
json解析拦截

### ISSUE THREAD

**Issue by folinwu2296** [liujingxing/okhttp-RxHttp#216]
本来应该返回  数组的
    {
    	"code":0,
    	"data":[],
    	"msg":"认证失败"
    }。
当token失效返回了  对象。这个怎么拦截呢。
    {
    	"code":1,
    	"data":{},
    	"msg":"认证失败"
    }

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8
