### ISSUE TITLE
Failed to resolve: rxhttp-2.5.4

### ISSUE THREAD

**Issue by Antecer** [liujingxing/okhttp-RxHttp#217]
如图,RxHttp2.5.4 无法添加

![image](https://user-images.githubusercontent.com/8684916/105666282-e0795f00-5f13-11eb-83ef-46d8c2a1b643.png)

2.5.3可以正常添加

**Comment by liujingxing** [comment]
2.5.3因为本地已经下载成功了；新版下载不成功，我也没有啥好办法，换个网络或者翻墙多试试。

**Comment by Antecer** [comment]
刚建立的新工程,都是刚刚才添加的,奇怪..
