### ISSUE TITLE
我调用百度人脸比对的接口它需要的是直接传一个json  数组，参数没有键，怎么传递?

### ISSUE THREAD

**Issue by honganxue** [liujingxing/okhttp-RxHttp#219]
正确的参数格式：  [{"face_type":"CERT","image":"9578f87153b16a7fa57ab300175bd4e9","image_type":"BASE64"},{"face_type":"LIVE","image":"9578f87153b16a7fa57ab300175bd4e9","image_type":"BASE64"}]

框架的传参总会带一个键

   {
       "iamge":"[{"face_type":"CERT","image":"9578f87153b16a7fa57ab300175bd4e9","image_type":"BASE64"},{"face_type":"LIVE","image":"9578f87153b16a7fa57ab300175bd4e9","image_type":"BASE64"}]"

   } 

请问要怎么传递？

**Comment by liujingxing** [comment]
`RxHttp.postJsonArray("/service/...").add()`
