### ISSUE TITLE
希望后续版本能突破rxhttp-compiler只会在本Module检索注解的限制

### ISSUE THREAD

**Issue by hegaojian** [liujingxing/okhttp-RxHttp#220]
个人觉得作者这个库挺好用的，能解决我平常请求中很多的疑难杂症。前段时间写了一个框架，其中的网络请求是用的RxHttp，但是因为rxhttp-compile注解的限制，无法将框架作为远程依赖使用，希望后续作者能突破该限制，谢谢了 👍

**Comment by liujingxing** [comment]
感谢肯定，不过很惭愧，我也很希望注解处理器能能跨module检索注解，但这是注解处理器自身的限制，无论是Glide、butterknife还是其它使用了注解处理器的库，都无法做到跨module检索注解；

目前最优的做法仅是base module依赖rrxhttp-compiler，这样上层都可以调用到RxHttp类；当然，你也可以多module同时依赖rxhttp-compiler，这样就会在每个module下都会生成RxHttp类。

**Comment by hegaojian** [comment]
感谢大佬的解答 👍
