### ISSUE TITLE
关于后台返回的json数据问题

### ISSUE THREAD

**Issue by HotBitmapGG** [liujingxing/okhttp-RxHttp#221]
现在遇到1个问题，就是正常情况下，后台返回的数据是 {"status":"0","msg":"成功","data":{}}，但是异常情况后台返回的数据是{"status":"0","msg":"很抱歉，您查看的商品找不到了","data":[]} 这样的，就会导致一直包json解析失败的异常，因为第一次使用这个框架，请问这个情况怎么处理

**Comment by liujingxing** [comment]
看这里 https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8

**Comment by HotBitmapGG** [comment]
@liujingxing 谢谢，已解决

**Comment by xuexirong** [comment]
@HotBitmapGG 请问你这个问题咋解决的 我也遇到了

**Comment by liujingxing** [comment]
@xuexirong 上面链接点进去

**Comment by xuexirong** [comment]
@liujingxing 好的 谢谢
