### ISSUE TITLE
[普通请求的进度条统一封装][协程的方式]

### ISSUE THREAD

**Issue by LatoAndroid** [liujingxing/okhttp-RxHttp#223]
作者你好，我看你的issue里面有rxjava的进度的统一方式（自定义observer），请问协程该怎么处理。我想到自定义ext去拓展，像这样
```
fun RxLifeScope.launchWithProgress(
    block: suspend CoroutineScope.() -> Unit,
    onError: ((Throwable) -> Unit)? = null
) {
    this.launch(block, onError, {
        //显示
    }, {
        //隐藏
    })
}
```
但是就拿不到onStart、onFinally回调了

而如果全部参数复制过来重新写
coroutineScope是private的，ext拿不到

**Comment by liujingxing** [comment]
没懂，你目前写的代码不就已经实现了吗？

**Comment by LatoAndroid** [comment]
因为你原来的方法是有onStart、onFinally回调的，我这么写这两个回调就拿不到了，感觉这样写的有点问题啊

**Comment by liujingxing** [comment]
你不是要统一封装吗？为啥还要拿到？就你现在的代码，处理下loading弹窗的显示与销毁不就ok了？
