### ISSUE TITLE
引入导致的问题

### ISSUE THREAD

**Issue by toutoumu** [liujingxing/okhttp-RxHttp#224]
lifecycleScope.launch {  }
rxLifeScope.launch {}
这两行代码同时调用会报错, 因为第一行代码执行是已经在 mInternalScopeRef 设置了值 因此
RxLife.kt文件中调用 mInternalScopeRef.get() as RxLifeScope 会报类型转换异常

**Comment by liujingxing** [comment]
这个暂时没有办法，同一个页面rxLifeScope与lifecycleScope不能混用，除非每次都新建rxLifeScope或lifecycleScope对象。
