### ISSUE TITLE
long类型数据失真

### ISSUE THREAD

**Issue by WaoSan** [liujingxing/okhttp-RxHttp#225]
作者你好!
JsonUtil(json.kt)类中Number.toAny()数据失真
```
fun Number.toAny(): Any {
    val d = toDouble()
    val i = d.toLong()// <<<问题在这里
    return if (d == i.toDouble() && i.toString().length == toString().length) i else d
}
```

**Comment by liujingxing** [comment]
确定是long类型失真，我测试到的是double类型失真，正在想办法修复

**Comment by WaoSan** [comment]
谢谢答复，我测试的时候是json对象有个long对象，你代码中是把这个long ----》toDouble然后再把这个double对象---> toLong。然后数据就精度丢失了

**Comment by liujingxing** [comment]
long多大？

**Comment by WaoSan** [comment]
1368815046190571522
这个是long类型的订单编号，用Java的duoble.valueof（）转换成double类型的，然后将这个double类型的longvaule（）可以得到你那个类中相同的结果

---原始邮件---
发件人: "liujingxing"<notifications@github.com&gt;
发送时间: 2021年3月8日(周一) 晚上9:33
收件人: "liujingxing/okhttp-RxHttp"<okhttp-RxHttp@noreply.github.com&gt;;
抄送: "Goshua"<863476604@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [liujingxing/okhttp-RxHttp] long类型数据失真 (#225)




 
long多大？

**Comment by liujingxing** [comment]
晓得了，long类型太大了，转double后用科学计数法表示就丢失精度了；下个版本修复，对于较大的数值，直接通过字符串传递。

**Comment by liujingxing** [comment]
你目前可以通过add方法传递，该方法是没问题的，addAll方法才有问题

**Comment by WaoSan** [comment]
好的，我明天试一下。非常感谢～



---原始邮件---
发件人: "liujingxing"<notifications@github.com&gt;
发送时间: 2021年3月8日(周一) 晚上9:50
收件人: "liujingxing/okhttp-RxHttp"<okhttp-RxHttp@noreply.github.com&gt;;
抄送: "Goshua"<863476604@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [liujingxing/okhttp-RxHttp] long类型数据失真 (#225)




 
你目前可以通过add方法传递，该方法是没问题的，addAll方法才有问题

**Comment by liujingxing** [comment]
RxHttp v2.5.7版本已修复
