### ISSUE TITLE
重写ResponseParse解析返回有数据，但是接收的时候报空指针

### ISSUE THREAD

**Issue by eternallyjie** [liujingxing/okhttp-RxHttp#226]
log如下，我重写的ResponseParse数据解析，解析结果是有数据的，不为null返回的，但是在接收端，却报了空指针，请问这是什么原因呢？

![image](https://user-images.githubusercontent.com/30895476/110905307-3d569a80-8345-11eb-9ed1-0bb75ef951d3.png)

具体的解析后的内容如下：
   {"address":"来福士广场 测试测试","confrimReceiveTime":"2020-03-20 17:01:00","contactName":"测试","contactPhone":"18726171085","createTime":"2020-03-20 15:51:47","discountList":[{"cardNo":"91060196","discountCouponId":135191,"discountCouponMoney":0.0,"discountCouponName":"30元抵价券","discountCouponType":1}],"discountMoney":23.0,"freightMoney":5.0,"icTradeNo":"L51S500041D6604","invoiceModel":{"invoiceId":0,"isOpenInvoice":0,"type":0},"orderBaseId":5259,"orderCode":"200320155147213852","orderGoodsList":[{"costPrice":18.0,"goodsBaseId":102,"goodsImage":"https://img.donco.com.cn/product/191101153544104309.jpg","goodsPrice":18.0,"goodsPropery":"500","goodsQuantity":1,"goodsRelationId":0,"goodsTitle":"生吐司","orderType":0,"productBaseId":46}],"orderMoney":23.0,"orderStatus":9,"orderType":2,"payMethod":0,"payMoney":0.0,"rebate":0.0,"remark":"","storeAddress":"新业路228号来福士中心B1层08号donco面包店","storeId":1,"storeName":"来福士店","storePhone":"0571-85153326","storeRelationId":500041,"tpP_OrderStatus":"0"}

**Comment by liujingxing** [comment]
看看具体报错日志，我猜是在成功回调里，出现的空指针异常，你再调试看看。

**Comment by eternallyjie** [comment]
> 看看具体报错日志，我猜是在成功回调里，出现的空指针异常，你再调试看看。

是在RxJava的onNext里面报的这个空指针，但是不知道为什么

**Comment by liujingxing** [comment]
看看代码

**Comment by eternallyjie** [comment]
> 看看代码

代码都是一样的

![image](https://user-images.githubusercontent.com/30895476/110907107-d981a100-8347-11eb-988d-be5053e49bbb.png)

然后就走到这个onError了。

就这一条数据这样

**Comment by liujingxing** [comment]
你要在onNext回调去调试，看看为啥哪个字段空指针

**Comment by eternallyjie** [comment]
> 你要在onNext回调去调试，看看为啥哪个字段空指针

排查到了，后台改了字段名，还用以前的字段解析，导致的。。。。。。。
