### ISSUE TITLE
如果有多个baseUrl怎么办？

### ISSUE THREAD

**Issue by FlyingYu-Z** [liujingxing/okhttp-RxHttp#227]
像正式服和测试服url

**Comment by liujingxing** [comment]
[多baseUrl，动态baseUrl，点击这里](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8)

**Comment by FlyingYu-Z** [comment]
好，感谢，但是仍然不能满足需求，希望在加解上加一个字段，isDebug，如果是debug模式则使用该url

**Comment by liujingxing** [comment]
动态baseurl不就满足了吗？在看看文档

**Comment by liujingxing** [comment]
亦或者，初始化的时候直接判断
```java
@DefaultDomain
public static final String baseUrl = BuildConfig.DEBUG ? "测试地址" : "正式地址";
```

**Comment by FlyingYu-Z** [comment]
我感觉还是不能满足，举个例子，现在有A公司和B公司两家公司的url，他们两家又分别有测试服url和正式服url，总的就是4个url，而目前的动态url只能用来区分两个公司的url，不能用来区分正式和测试url

所以有个建议，如下：
@Domain(name = "Google"，hasDebug=true, normalUrl="http://test.test/debug",debugUrl="http://test.test/debug",releaseUrl="http://test.test/debug") 

当hasDebug为false时，直接取normalUrl
当hasDebug为true时，再根据BuildConfig.DEBUG来判断该采用正式服或者测试服url

**Comment by FlyingYu-Z** [comment]
好，解决了，感谢
