### ISSUE TITLE
接入SOAP问题

### ISSUE THREAD

**Issue by Gc-JingX** [liujingxing/okhttp-RxHttp#230]
项目如果想要接入访问soap 协议，怎么配置，现在是否支持了呢

**Comment by liujingxing** [comment]
必须支持啊，RxHttp.postBody("").setBody()，可发送任意类型RequestBody，对于服务端返回的xml数据，通过配置Xml类型的Converter，即可正常解析。

**Comment by Gc-JingX** [comment]
可以提供个demo吗，我这边尝试了是一直报500的，

**Comment by Gc-JingX** [comment]
自己写了个拦截器封装提交的请求可以了

**Comment by Gc-JingX** [comment]
谢谢了
