### ISSUE TITLE
可以取消下载吗？

### ISSUE THREAD

**Issue by leestars** [liujingxing/okhttp-RxHttp#233]
有没有API取消下载？

**Comment by liujingxing** [comment]
取消请求，就是取消下载
https://github.com/liujingxing/okhttp-RxHttp/wiki/%E5%85%B3%E9%97%AD%E8%AF%B7%E6%B1%82

**Comment by leestars** [comment]
fun downloadFile(position: Int, url: String, filename: String, type: Int) {
        launch({
            val factory =
                DownloadFactory(App.context, filename, type)
            RxHttp.get(url)
                .tag(url)
                .toDownload(factory, Dispatchers.Main) {
                    LogUtil.e(TAG, "download url::${url}|progress::${it.progress}")
                }.await()
        })
    }`

    fun cancelDownload(url: String) {
        RxHttpPlugins.cancelAll(url)
    }`

调用cancel之后 进度还是在打印

**Comment by liujingxing** [comment]
协程需要你拿到Job对象，然后调用cancel方法，如下：
```
    val job: Job? = null
    fun downloadFile(position: Int, url: String, filename: String, type: Int) {
       val job = launch({
            val factory =
                DownloadFactory(App.context, filename, type)
            RxHttp.get(url)
                .tag(url)
                .toDownload(factory, Dispatchers.Main) {
                    LogUtil.e(TAG, "download url::${url}|progress::${it.progress}")
                }.await()
        })
    }

    fun cancelDownload(url: String) {
       job?.cancel()  //关闭协程  
    }
```

**Comment by liujingxing** [comment]
我前面说的不是很正确，取消请求不等于中断下载，`RxHttpPlugins.cancelAll(url)`只是取消请求而已(请求还未结束前调用才有效)。
如果要中断下载，对于协程就是关闭协程，对于RxJava，则是断开RxJava管道。
