### ISSUE TITLE
自定义parser后，有asParser...就是生成不了asResponse

### ISSUE THREAD

**Issue by Swordce** [liujingxing/okhttp-RxHttp#236]
![image](https://user-images.githubusercontent.com/16829238/113999882-0a90bb00-988d-11eb-89f9-cdc9f4f4fbea.png)

**Comment by liujingxing** [comment]
rxhttp-compiler只会在本Module检索注解，检索不到，就不会生成相关方法，故请不要在A Module依赖rxhttp-compiler，却在B Module使用注解

**Comment by Swordce** [comment]
好吧，确实是这样，我这个parser放到base_module了，其他module要使用asXxx方法的话，是不是也要加个parser类

**Comment by liujingxing** [comment]
其它module依赖baseModule就好了

**Comment by Swordce** [comment]
多谢，已经解决
