### ISSUE TITLE
闪退问题，InternalCache空指针

### ISSUE THREAD

**Issue by SuperXpher** [liujingxing/okhttp-RxHttp#237]
打开app闪退，清掉应用数据后恢复正常。请问是库本身问题还是我使用上可能存在问题？报错信息如下：

` Attempt to invoke interface method 'okhttp3.Response rxhttp.wrapper.cahce.InternalCache.get(okhttp3.Request, java.lang.String)' on a null object reference
rxhttp.wrapper.intercept.CacheInterceptor.getCacheResponse(CacheInterceptor.kt:72)
 rxhttp.wrapper.intercept.CacheInterceptor.beforeReadCache(CacheInterceptor.kt:52)
 rxhttp.wrapper.intercept.CacheInterceptor.intercept(CacheInterceptor.kt:28)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
 okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
 java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 java.lang.Thread.run(Thread.java:929)
`

**Comment by liujingxing** [comment]
没有配置缓存目录及全局缓存模式
