### ISSUE TITLE
data里面直接是数组怎么解析呢？

### ISSUE THREAD

**Issue by yanpengqing** [liujingxing/okhttp-RxHttp#239]
比如：
{
code:0,
msg:“成功”,
data:[{
id:"1"
}]
}

**Comment by liujingxing** [comment]
RxJava (Java写法)`toResponseList(Class<T>)`；
RxJava (kotlin写法 )`asResponse<List<T>>()`
Kotlin 协程`toResponse<List<T>>()`

**Comment by yanpengqing** [comment]
.asResponseList(FenceEntity.class)
 为啥赋值不成功呢

**Comment by liujingxing** [comment]
报什么错？检查下数据结构是否对上

**Comment by yanpengqing** [comment]
不会报错，log打印看到了返回的数据，字段肯定对的上，bean类始终没有赋值成功。

**Comment by yanpengqing** [comment]
我把代码改成 .asResponse(List.class)
解析成功
我想直接拿到List<FenceEntity> 要怎么做？

**Comment by yanpengqing** [comment]
我把代码改成 .asResponse(List.class)
解析成功
我想直接拿到 list<FenceEntity> 要怎么做？

**Comment by liujingxing** [comment]
实在没搞懂你的问题
```java
RxHttp.get("...")
        .add("key", "value")
        .asResponseList(FenceEntity.class)
        .subscribe(list-> {
              
        })
```
这样不行？

**Comment by yanpengqing** [comment]
> 实在没搞懂你的问题
> ```java
> RxHttp.get("...")
>     .add("key", "value")
>     .asResponseList(FenceEntity.class)
>     .subscribe(list-> {
>               
>     })
> ```
> 这样不行？

这样试过，不知道为啥没赋值，里面字段全是空的

**Comment by liujingxing** [comment]
list.size()==0？还是FenceEntity对象里面的字段是空的？把接口返回数据及FenceEntity类发出来，对比下就知道了

**Comment by yanpengqing** [comment]
> list.size()==0？还是FenceEntity对象里面的字段是空的？把接口返回数据及FenceEntity类发出来，对比下就知道了

list size不为0，是对象里字段全是空的

数据如下：
{
    "Data": [
        {
            "CompanyId": "MDAwMzItMTkwNjI0MTEwMzMzMzLyZ1VuaXQ=",
            "DigitalNumber": "100007188",
            "FarmId": "MDE4NjgtMjAwMjA4MTYxNzU1MS1PcmdVbml0",
            "Id": "MTQ1MDktMjEwNDNS1GZW5jZUxpc3Q=",
            "IsEnabled": 1,
            "Name": "A4",
            "Number": "A4",
            "ShedId": "MDE4ODItMjAwMjA4M1Mi1PcmdVbml0",
            "Type": 1,
            "WorkshopId": "MDAwMDMtMjAxDMxMTAzMS1Xb3Jrc2hvcExpc3Q="
        },
        {
            "CompanyId": "MDAwMzItMMzMzMzLU9yZ1VuaXQ=",
            "FarmId": "MDE4NjgtM4MTYxNzU1MTc1NS1PcmdVbml0",
            "Id": "U4ODME1MTUxNTE1MTUxNS1GZW5jZUxpc3Q=",
            "IsEnabled": 1,
            "Name": "LKP-PZ-1-4",
            "Number": "LKP-PZ-1-4",
            "ShedId": "MDE4NzctMTgzOC1PcmdVbml0",
            "Type": 0,
            "WorkshopId": "MDAwMDItMjAxOTQzLVdvcmtzaG9wTGlzdA=="
        }
    ],
    "Msg": "查询成功",
    "PageIndex": 1,
    "PageSize": 2,
    "PageTotalCount": 5,
    "Status": 200,
    "Success": true,
    "Totle": 10
}

public class FenceEntity{
    public String id;
    public String companyId;
    public String farmId;
    public String shedId;
    public String workshopId;
    public int type;
    public String name;
    public String number;
    public String digitalNumber;
    public int isEnabled;
   // get set 省略
}

请求如下
   .asResponseList(FenceEntity.class)
                .to(RxLife.toMain(this))  
                .subscribe(FenceList -> {
                  //这里能拿到list的size不为0，里面的条目字段全是空的
                }

**Comment by yanpengqing** [comment]
> list.size()==0？还是FenceEntity对象里面的字段是空的？把接口返回数据及FenceEntity类发出来，对比下就知道了

感谢回复。
问题现解决了
服务器返回的数据每一个字段第一个字母是大写的
我用插件生成的bean类都是小写的
所以对应不上
另外请教一下有没有什么办法忽略字段的大小写？

**Comment by liujingxing** [comment]
@SerializedName 注解了解一下

**Comment by yanpengqing** [comment]
> @SerializedName 注解了解一下

    @ColumnInfo(name = "company_id")
    @SerializedName("CompanyId")
    private String companyId;
这样确定可以，感觉这样的话还不如直接修改字段名。
每次这样写挺麻烦的。
有没有其它方法可以不区分大小写直接解析成功的？

**Comment by liujingxing** [comment]
没有，如果有，请告诉我

**Comment by yanpengqing** [comment]
> 没有，如果有，请告诉我

好的，麻烦了。换了个插件不会忽略大小写生成bean类。暂时先这样吧。
