### ISSUE TITLE
关于cookie的保存发现一个使用中的疑惑

### ISSUE THREAD

**Issue by ppg408331701** [liujingxing/okhttp-RxHttp#240]
改造旧项目的时候，旧项目用的cookie管理工具是okgo的SPCookieStore
参考 [SPCookieStore](https://github.com/jeasonlzy/okhttp-OkGo/blob/e34c2fa150dba4fa6e9460439f6c30adeea48225/okgo/src/main/java/com/lzy/okgo/cookie/store/SPCookieStore.java)

目前rxhttp只有返回头中有Set-Cookie,就会马上用最新的覆盖之前保存的。

```
 @Override
    public void saveCookie(HttpUrl url, List<Cookie> cookies) {
        final String host = url.host();
        if (memoryCache != null) { //开启了内存缓存，则将cookie写入内存
            memoryCache.put(host, cookies);
        }

        DiskLruCache diskCache = getDiskLruCache();
        if (diskCache != null) { //开启了磁盘缓存，则将cookie写入磁盘
            DiskLruCache.Editor editor = null;
            try {
                editor = diskCache.edit(md5(host));
                if (editor == null) {
                    return;
                }
                writeCookie(editor, cookies);
                editor.commit();
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                abortQuietly(editor);
            }
        }
    }
```

我当前遇到一个问题，我们的就项目中某些接口，Set-Cookie会返回2种不同的SessionId 。
一种是      Set-Cookie: ASP.NET_SessionId=ipr4xtadi5m4v3lefibizpdg; path=/; HttpOnly; SameSite=Lax
另一种是  Set-Cookie: AlteonP=A1xiVwkNwKzKXFk5A9Zffw$$; Path=/

其中ASP.NET_SessionId才是可用的，AlteonP是后台接入的第三方服务返回的。
![QQ截图20210427114208](https://user-images.githubusercontent.com/16531268/116181722-b2432f80-a74d-11eb-80b1-c3f401515aef.png)

目前旧项目使用SPCookieStore时，没出问题，但是为什么会没出问题，我目前没搞懂

请问rxhttp有对这种情况有处理吗？

如果没有是否我只能通过重写CookieStore的方式解决？

**Comment by ppg408331701** [comment]
debug了一下，
发现SPCookieStore会以HashMap的数组储存cookie，所以两个cookie都存了起来
![image](https://user-images.githubusercontent.com/16531268/116182377-c4719d80-a74e-11eb-9e98-cafbd07bf5ab.png)
会不会是因为这个？

**Comment by liujingxing** [comment]
看了下okgo的方案，它会把相同域名下的新旧cookie统统都保存，而RxHttpd提供的[CookieStore](https://github.com/liujingxing/okhttp-RxHttp/blob/master/rxhttp/src/main/java/rxhttp/wrapper/cookie/CookieStore.java)方案是新cookie替换旧cookie，两个方案都不能算完美，不能满足所有的需求，好在，这是开放性的问题，选择适合自己的方案就好。

**Comment by ppg408331701** [comment]
确实如此，我根据SPCookieStore重写一下好了

**Comment by liujingxing** [comment]
仔细一想，okgo的方案好像更符合实际业务逻辑，后续我在琢磨下，感谢提出。

**Comment by ppg408331701** [comment]
我也觉得，因为我用pc浏览器测试的时候，浏览器会保存同一个host下的所有cookie的。okgo的方案更接近浏览器的做法
