### ISSUE TITLE
2.5.7 关于日志打印不显示request start部分的问题

### ISSUE THREAD

**Issue by jousen** [liujingxing/okhttp-RxHttp#245]
RxHttp.init(okHttpClient, true);
开启日志后，只显示I/RxHttp: <------ rxhttp/2.5.7 okhttp/4.9.1 request end ------>之后的日志部分。
但是之前的 request start 的提交的参数部分，在debug模式看到在LogUtil 143行处可以看到值是正常生成的数据，
但是Platform.get().logd(TAG, builder.toString()); 这行完成后，无法在Logcat里看到信息
请问这是什么原因呢？
感谢回复~

**Comment by liujingxing** [comment]
请求开始/结束日志，都是用的原生Log类打印的，只不过是日志等级不一样而已，找不到日志的话，可能需要你自己去找找原因，可以自己打印个日志试试。

**Comment by jousen** [comment]
感谢回复，最后加了拦截器输出log是正常的，这个问题还不知道是怎么回事。辛苦了
