### ISSUE TITLE
统一获取所有的请求参数？

### ISSUE THREAD

**Issue by bingdu0** [liujingxing/okhttp-RxHttp#246]
1.如何统一获取每个请求参数，get put post 等RxHttp 内部14种 的请求参数和值。
2.如何同步的方式获取返回结果
3.自定义Param getRequestBody() 可不可以在子线程中执行

**Comment by liujingxing** [comment]
第一、第三点，请直接描述你遇到的场景
第二点，请查看[指定请求、回调线程](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%8C%87%E5%AE%9A%E8%AF%B7%E6%B1%82%E3%80%81%E5%9B%9E%E8%B0%83%E7%BA%BF%E7%A8%8B)

**Comment by bingdu0** [comment]
第一个和第三个是同一个问题。我想获取每个请求的参数和值，为每个参数和值加密，然后看文档发现了可以自定义Param，然后重写getRequestBody() 可以获取key value，但是现在项目中用了好多postJson postForm  putJson 等，自定义完成之后 我还要一个个的改。我现在用拦截器拦截了post 和get ，我就想知道RxHttp有没有提供统一获取所有请求的参数的方法。

**Comment by liujingxing** [comment]
设置公共参数接口可以获取，如下：
```java
RxHttp.setOnParamAssembly(param -> {                             
    if (param instanceof FormParam) {                            
        FormParam formParam = (FormParam) param;                 
        List<KeyValuePair> bodyParam = formParam.getBodyParam(); 
    } else if (param instanceof JsonParam) {                     
        JsonParam jsonParam = (JsonParam) param;                 
        Map<String, Object> bodyParam = jsonParam.getBodyParam();
    } else {                                                     
                                                                 
    }                                                            
    return param;                                                
});                                                              
```

**Comment by bingdu0** [comment]
> 设置公共参数接口可以获取，如下：
> 
> ```java
> RxHttp.setOnParamAssembly(param -> {                             
>     if (param instanceof FormParam) {                            
>         FormParam formParam = (FormParam) param;                 
>         List<KeyValuePair> bodyParam = formParam.getBodyParam(); 
>     } else if (param instanceof JsonParam) {                     
>         JsonParam jsonParam = (JsonParam) param;                 
>         Map<String, Object> bodyParam = jsonParam.getBodyParam();
>     } else {                                                     
>                                                                  
>     }                                                            
>     return param;                                                
> });                                                              
> ```

嗯嗯，这个我看文档我也试了 ，它不是在子线程吗？如果我在这里面做网络请求 ，同步的方式获取返回结果
`val appKeyData = RxHttp.get(“str_app”)
                    .setDomainToAppKeyIfAbsent()
                   // .setAssemblyEnabled(false)
                    .execute(SimpleParser<String>(String::class.java))`
                    
这个时候就会报一个错  
`at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
at rxhttp.wrapper.param.RxHttp.execute(RxHttp.java:473)
at rxhttp.wrapper.param.RxHttp.execute(RxHttp.java:477)
at rxhttp.RxHttpPlugins.apply(RxHttpPlugins.java:94)
at rxhttp.RxHttpPlugins.onParamAssembly(RxHttpPlugins.java:68)
at rxhttp.wrapper.param.AbstractParam.buildRequest(AbstractParam.java:219)
at rxhttp.wrapper.param.RxHttp.buildRequest(RxHttp.java:504)
at rxhttp.wrapper.param.RxHttp.newCall(RxHttp.java:495)
at rxhttp.wrapper.await.AwaitImpl.await(AwaitImpl.kt:23)`

**Comment by liujingxing** [comment]
这个方法在主线程执行，你为啥要在这里发请求呢？详细说说你的需求。

**Comment by bingdu0** [comment]
> 这个方法在主线程执行，你为啥要在这里发请求呢？详细说说你的需求。

涉及到公司的加密，我在QQ上跟你说一下。

**Comment by bingdu0** [comment]
> 这个方法在主线程执行，你为啥要在这里发请求呢？详细说说你的需求。

因为我要在这里请求接口获取一个key ，这个key 是动态的，通过这个key 把所有的参数加密。
