### ISSUE TITLE
像 这种 如何 使用 rxhttp???

### ISSUE THREAD

**Issue by scaPEGoatno** [liujingxing/okhttp-RxHttp#50]
https://github.com/Notsfsssf/Pix-EzViewer/blob/master/app/src/main/java/com/perol/asdpl/pixivez/networks/RestClient.kt

**Comment by liujingxing** [comment]
文件内容太多，你具体指的哪些？

**Comment by scaPEGoatno** [comment]
> 文件内容太多，你具体指的哪些？

里面几个不同的okhttpclient,需要设置不同的dns...

**Comment by liujingxing** [comment]
目前暂不支持配置多个okhttpclient对象，后续版本会考虑这种情况

**Comment by liujingxing** [comment]
v2.2.5版本已支持配置多个OkHttpClient对象，且方便切换，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#okclient
