### ISSUE TITLE
同一个请求返回不同格式的json怎么处理？

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#52]

**Comment by liujingxing** [comment]
成功  `{"code":"100","msg":"success","data":{}}`
失败 ` {"code":"101","msg":"fail","data":[]}`
类似这样的？

如果是的话，初始化的时候，加入下面这段代码就好了
`RxHttp.setResultDecoder(result -> result.replace(",\"data\":[]", ""));`

如果不是，请详细描述你的问题

**Comment by chenyinchao** [comment]
可能是接口规范问题，应该不会有这种情况出现

**Comment by linmomo** [comment]
同情况，后台是php后台，请求成功时候data为json对象，返回{}，错误的时候返回字符串“”

**Comment by liujingxing** [comment]
初始化的时候，加入下面这段代码就好了
```java
RxHttp.setResultDecoder(result -> result.replace(",\"data\":\"\"", ""));
```
该回调，每次请求返回都会执行

**Comment by linmomo** [comment]
好的，问题已解决，麻烦作者了
