### ISSUE TITLE
关于下载的问题

### ISSUE THREAD

**Issue by xiaolanbuzaiaixinyi** [liujingxing/okhttp-RxHttp#54]
2020-01-09 15:38:34.914 15484-15484/com.yunshi.phone E/TAG: currentProgress100
2020-01-09 15:38:34.914 15484-15484/com.yunshi.phone E/TAG: currentSize119848290
2020-01-09 15:38:34.914 15484-15484/com.yunshi.phone E/TAG: totalSize119848290
2020-01-09 15:38:34.919 15484-15484/com.yunshi.phone E/TAG: currentProgress-1
2020-01-09 15:38:34.919 15484-15484/com.yunshi.phone E/TAG: currentSize-1
2020-01-09 15:38:34.919 15484-15484/com.yunshi.phone E/TAG: totalSize-1
到下载全部完成后为啥这个会等于-1

**Comment by liujingxing** [comment]
-1是内部用来判断是否下载完成的

**Comment by xiaolanbuzaiaixinyi** [comment]
好的，了解了，谢谢大佬

**Comment by liujingxing** [comment]
看下你的代码，按道理你是收不到-1的回调的

**Comment by xiaolanbuzaiaixinyi** [comment]
String destPath = getExternalCacheDir() + "/" + "Miaobo.apk";
long length = new File(destPath).length(); //已下载的文件长度
RxHttp.get("http://update.9158.com/miaolive/Miaolive.apk")
    .setRangeHeader(length)  //设置开始下载位置，结束位置默认为文件末尾
    .asDownload(destPath, length, progress -> {
        //下载进度回调,0-100，仅在进度有更新时才会回调
        int currentProgress = progress.getProgress(); //当前进度 0-100
        long currentSize = progress.getCurrentSize(); //当前已下载的字节大小
        long totalSize = progress.getTotalSize();     //要下载的总字节大小
    }, AndroidSchedulers.mainThread()) //指定主线程回调
    .subscribe(s -> { //s为String类型
        //下载成功，处理相关逻辑
    }, throwable -> {
        //下载失败，处理相关逻辑
    });

我用的就是你这个方式请求的，但是currentProgress从0到100后会再次返回一个-1

**Comment by liujingxing** [comment]
刚仔细回看了代码，没毛病哈，最后一个代表下载完成，会带上本地存储路径

**Comment by liujingxing** [comment]
刚仔细回看了代码，没毛病哈，最后一个-1代表下载完成，会带上本地存储路径

**Comment by xiaolanbuzaiaixinyi** [comment]
大佬有查到为啥这样返回吗？

**Comment by xiaolanbuzaiaixinyi** [comment]
但是这个是在进度的回调中返回的。就是在asDownload中最后返回-1

**Comment by liujingxing** [comment]
尽管它不是很友好，但仍然属于正常，后续会考虑优化一下。当前的话，你判断下-1不处理就好了。

**Comment by xiaolanbuzaiaixinyi** [comment]
好的  谢谢大佬提供的库
