### ISSUE TITLE
返回值类型修改，有懂的么

### ISSUE THREAD

**Issue by Leavds** [liujingxing/okhttp-RxHttp#55]
1  使用asParser 编译的时候报这个错误
![image](https://user-images.githubusercontent.com/26810069/72134995-633e8300-33c0-11ea-9968-6c63746e1d9a.png)
2 返回值类型咋改
3 asObject  传入class，我还以为是传入啥返回啥，能不能加个 传入啥返回啥，现在这类型多 限制也多直接传入泛型类不好么？

**Comment by liujingxing** [comment]
asObject方法就是你传啥就返回啥。。另外，把你的ResponseParser类贴出来看看

**Comment by Leavds** [comment]
拷的https://juejin.im/post/5ded221a518825125d14a1d4#heading-25   5.1的东西  一样的

**Comment by liujingxing** [comment]
看下你的用法，或者加我QQ 327744707

**Comment by Leavds** [comment]
加你了

**Comment by Leavds** [comment]
直接编译都过不去  
![image](https://user-images.githubusercontent.com/26810069/72140300-6db24a00-33cb-11ea-83ce-a9b69d5f54e0.png)
![image](https://user-images.githubusercontent.com/26810069/72140335-83277400-33cb-11ea-913c-96305ce4c86e.png)

**Comment by liujingxing** [comment]
![image](https://user-images.githubusercontent.com/7237396/72140557-f92bdb00-33cb-11ea-88a4-94d20bc9b31b.png)
这里要统一

**Comment by liujingxing** [comment]
要提供对应的构造方法

**Comment by Leavds** [comment]
ok  看的时候 没注意
