### ISSUE TITLE
注解处理器不能在Library module中生成Rxhttp

### ISSUE THREAD

**Issue by ITFlyPig** [liujingxing/okhttp-RxHttp#57]
我想将网络请求框架放在module中，appmodule引用它，但是中间封装一层，屏蔽具体的网络实现库，便于将来替换。但是在module中无法生成Rxhttp类。

**Comment by liujingxing** [comment]
要想在任意Module中生成RxHttp类，首先要在该Module中依赖注解处理器
`annotationProcessor 'com.rxjava.rxhttp:rxhttp-compiler:1.4.1'` ,随后需要在该Module中使用任意注解，最后rebuild即可。  
`注：注解的使用和注解处理器要放在同一个Module`
