### ISSUE TITLE
能不能把一次网络请求解析成的Bean对象，在别的地方都可以调用，避免多次请求网络

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#58]

**Comment by liujingxing** [comment]
把拿到的Bean对象，用单例存起来不行吗?或者你可以利用RxHttp的缓存，有缓存就不会请求了。https://github.com/liujingxing/okhttp-RxHttp/wiki/%E7%BC%93%E5%AD%98%E7%AD%96%E7%95%A5

**Comment by chenyinchao** [comment]
我写了单例，但是读取单例的值还是空的，是不是还要赋值啊，不知怎么搞

**Comment by liujingxing** [comment]
你没给单例赋值怎么行。看下你的代码

**Comment by chenyinchao** [comment]
已经解决了，谢谢你了，我因为解析后自动填入了
