### ISSUE TITLE
建议支持缓存

### ISSUE THREAD

**Issue by FrozenFreeFall** [liujingxing/okhttp-RxHttp#59]
现在支持缓存么？我知道现在很多都支持缓存，但是我说的缓存，只是API一句话的事情，并不是自己去弄.

**Comment by liujingxing** [comment]
已经支持了  ，详情  https://github.com/liujingxing/okhttp-RxHttp/wiki/%E7%BC%93%E5%AD%98%E7%AD%96%E7%95%A5
