### ISSUE TITLE
您好，有个小需求

### ISSUE THREAD

**Issue by Power-Android** [liujingxing/okhttp-RxHttp#60]
如何添加统一的请求进度条，希望在onstart()里开始显示加载进度条，在onnext()/onerror()里取消进度条。
现在想到的办法是在.subscribewith()方法里传入自定义observe继承ResourceObserver，拿到onstart，希望可以在subscribe()/subscribewith()添加实现进度条监听的实现方法。辛苦~

**Comment by liujingxing** [comment]
上传用upload操作符，下载用download操作符，文档有介绍的，你看下

**Comment by Power-Android** [comment]
> 上传用upload操作符，下载用下载操作符，文档有介绍的，你看下

这个只是涉及到了上传和下载，如果是普通的请求呢？或者需要自定义的进度条样式呢？

**Comment by liujingxing** [comment]
你说的是loading弹窗吧。有两种方式
```java
RxHttp.get("/service/...")
    .asString()
    .observeOn(AndroidSchedulers.mainThread())
    .doOnSubscribe(disposable -> {
        //请求开始，当前在主线程回调
    })
    .doFinally(() -> {
        //请求结束，当前在主线程回调
    })
    .as(RxLife.as(this))  //感知生命周期
    .subscribe(pageList -> {
        //成功回调，当前在主线程回调
    }, (OnError) error -> {
        //失败回调，当前在主线程回调
    });
```

或者，自定义Observer对象
```java
public abstract class LoadingObserver<T> implements Observer<T> {

    @Override
    public void onSubscribe(Disposable d) {
        //请求开始
    }


    @Override
    public void onNext(T t) {
        //请求成功
    }

    @Override
    public void onError(Throwable e) {
        //请求失败
    }

    @Override
    public void onComplete() {
        //请求完成  注：请求失败时，本方法不会调调
    }
}
```
然后在订阅回调的地方传入自定义的Observer即可

**Comment by Power-Android** [comment]
> 你说的是loading弹窗吧。有两种方式
> 
> ```java
> RxHttp.get("/service/...")
>     .asString()
>     .observeOn(AndroidSchedulers.mainThread())
>     .doOnSubscribe(disposable -> {
>         //请求开始，当前在主线程回调
>     })
>     .doFinally(() -> {
>         //请求结束，当前在主线程回调
>     })
>     .as(RxLife.as(this))  //感知生命周期
>     .subscribe(pageList -> {
>         //成功回调，当前在主线程回调
>     }, (OnError) error -> {
>         //失败回调，当前在主线程回调
>     });
> ```
> 
> 或者，自定义Observer对象
> 
> ```java
> public abstract class LoadingObserver<T> implements Observer<T> {
> 
>     @Override
>     public void onSubscribe(Disposable d) {
>         //请求开始
>     }
> 
> 
>     @Override
>     public void onNext(T t) {
>         //请求成功
>     }
> 
>     @Override
>     public void onError(Throwable e) {
>         //请求失败
>     }
> 
>     @Override
>     public void onComplete() {
>         //请求完成  注：请求失败时，本方法不会回调
>     }
> }
> ```
> 
> 然后在订阅回调的地方传入自定义的Observer即可

好的，感谢！
