### ISSUE TITLE
你好，请问请求有回调监听吗，我需要请求

### ISSUE THREAD

**Issue by qingqingziyu** [liujingxing/okhttp-RxHttp#61]
请问请求有回调监听吗，我需要请求进度条，非上传下载那种，就是普通请求，要加载框显示当前请求

**Comment by liujingxing** [comment]
3.3.3章节，https://juejin.im/entry/5deda783f265da339a1a980b，或者自定义Observer对象

**Comment by liujingxing** [comment]
自定义Observer对象，或者查看3.3.3章节https://juejin.im/entry/5deda783f265da339a1a980b

**Comment by qingqingziyu** [comment]
看到了，谢谢大佬
