### ISSUE TITLE
请问怎么自定义get请求的param，进行加密

### ISSUE THREAD

**Issue by qingqingziyu** [liujingxing/okhttp-RxHttp#62]
文档说用NoBodyParam，但是我看了下这个，不知道什么用，可以方便发个教程吗

**Comment by liujingxing** [comment]
Demo增加了示例，请查看：https://github.com/liujingxing/okhttp-RxHttp/blob/master/app/src/main/java/com/example/httpsender/param/GetEncryptParam.java

写好后，只需调用`RxHttp.getEncrypt("/service/...")`方法发送请求即可
