### ISSUE TITLE
解密回调会执行两次

### ISSUE THREAD

**Issue by boomstack** [liujingxing/okhttp-RxHttp#65]
```java
        RxHttp.setResultDecoder(new Function<String, String>() {
            @Override
            public String apply(String s) throws Exception {
                return s;
            }
        });
```
我再demo的RxHttpManager的init方法里加了这么一个解密的回调，打断点return s;这一行固定的会被执行两次

**Comment by liujingxing** [comment]
这是正常的，因为你调用`RxHttp.setDebug(true)`方法开启了Debug模式，关闭debug模式，就只会回调一次。

**Comment by boomstack** [comment]
> 这是正常的，因为你调用`RxHttp.setDebug(true)`方法开启了Debug模式，关闭debug模式，就只会回调一次。

赞👍

**Comment by Wingge** [comment]
> > 这是正常的，因为你调用`RxHttp.setDebug(true)`方法开启了Debug模式，关闭debug模式，就只会回调一次。
> 
> 赞👍

关了debug就可以了？我的还是两次回调的

**Comment by liujingxing** [comment]
@Wingge 关闭debug模式就仅执行一次，如果执行两次，那就去调试吧
