### ISSUE TITLE
RxHtpp如何写到model层，也就是说怎么做到不同页面请求同一个api数据，避免多次调用

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#68]

**Comment by liujingxing** [comment]
你是想问RxLife怎么在model层用吧？可以看这里https://github.com/liujingxing/rxjava-RxLife

**Comment by chenyinchao** [comment]
MVP的model层，是写网络请求的，就可以在不同的presenter去调用同一个网络请求，避免重复代码。我现在是在presenter层写RxHttp网络请求，但我有多个位置要使用这个RxHttp网络请求，我该怎么写呢？是把这个RxHttp写在model层，再写回调给presenter吗

可以看这篇文章：https://blog.csdn.net/smile_Running/article/details/94724540

**Comment by liujingxing** [comment]
你直接在model层用会有什么问题吗？

**Comment by liujingxing** [comment]
如果某个接口，会有多个地方调用，则可以封装成静态方法，如下：
```java
public class HttpWrapper {

    //检查更新
    public static Observable<Update> checkUpdate() {
        return RxHttp.get(CHECK_UPDATE)
            .add("curVersion", BuildConfig.VERSION_NAME)
            .add("id", Channel.getBundleId())
            .add("devType", "android")
            .asResponse(Update.class)
            .observeOn(AndroidSchedulers.mainThread());
    }
}
```

然后调用的方法，订阅回调即可

**Comment by chenyinchao** [comment]
@liujingxing  拿到Observable，非常感谢，我知道啦！
