### ISSUE TITLE
你好，多module时,在不同模块里使用自定义Response注解遇到点问题

### ISSUE THREAD

**Issue by abcdisgreat** [liujingxing/okhttp-RxHttp#70]
测试的时候 A 依赖 B,  B 依赖 C , 如果B 和 C中定义不同的ResponseB，ResponseC,结果ReBuild以后只生成了ResponseB的，不知道哪里出了问题

**Comment by liujingxing** [comment]
理解下这句话，你就知道问题所在了
![image](https://user-images.githubusercontent.com/7237396/75231778-06bce900-57f1-11ea-9982-38dff6255932.png)

https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ

**Comment by abcdisgreat** [comment]
谢谢，确实没看仔细。 我发现ResponseC也生成了，但是只能在C模块使用。而ResponseB却可以在A中正常使用
