### ISSUE TITLE
你好，我测试使用putForm 和deleteForm时add参数没生效，接口报参数丢失

### ISSUE THREAD

**Issue by abcdisgreat** [liujingxing/okhttp-RxHttp#71]
通过key value 和map 都试过了

**Comment by liujingxing** [comment]
RxHttp版本多少？接口报参数丢失，并不意味着你添加的参数丢失了。具体丢没丢失，过滤`RxHttp`查看日志就知道(需要设置RxHttp.setDebug(true))

**Comment by abcdisgreat** [comment]
![image](https://user-images.githubusercontent.com/33865977/75309494-2a813d00-588c-11ea-844a-dcd441befb53.png)
日志是这样的，为了正常请求要手动在url后面拼?tenancyId=xx

**Comment by liujingxing** [comment]
那你就应该用get请求，只有get/head请求参会把add方法添加的参数，拼接在url后面发送出去

**Comment by abcdisgreat** [comment]
@liujingxing 还有个小问题向请教下，像post 请求能添加一个直接传requestBody的方法吗

**Comment by liujingxing** [comment]
有想过添加这个方法，但是这样做的话，就没法添加公共参数了，所以就放弃了这个想法。如果你要自定义requestBody，可以自定义Param，重写getRequestBody()方法即可。详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param
