### ISSUE TITLE
文件下载超时

### ISSUE THREAD

**Issue by fengxiaozheng** [liujingxing/okhttp-RxHttp#72]
下载大一点文件时，二三十兆就会超时（用的是带进度的下载）

**Comment by liujingxing** [comment]
超时这个就是代码的问题了。首先，检查下网络是否顺畅，如果顺畅，那就换个下载地址试试(Demo里有下载链接)；如果网络不顺畅，可以适当加长超时时间，超时时间的配置看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/%E8%B6%85%E6%97%B6%E8%AE%BE%E7%BD%AE

**Comment by fengxiaozheng** [comment]
在同一个网络环境下，用网页打开能下载成功，用手机就是超时，下载一半多的时候就停住了，过会就超时

**Comment by fengxiaozheng** [comment]
![image](https://user-images.githubusercontent.com/18062197/75430288-1457a780-5986-11ea-844f-09674e17b80c.png)

**Comment by liujingxing** [comment]
你把超时时间设置长一点试试。另外，方便的话，把下载链接发出来，我这边试试。
