### ISSUE TITLE
OKHttp4.4.0会导致缓存功能失效

### ISSUE THREAD

**Issue by caiyoufei** [liujingxing/okhttp-RxHttp#73]
好像是DiskLruCache.create方法没有了，导致缓存文件夹都无法创建了

**Comment by caiyoufei** [comment]
另外还想问大佬一个问题，就是全局统一处理服务器的业务CODE应该放在哪里比较好呢？
比如，账号过期需要重新登录，这个业务code在哪里处理呢

**Comment by liujingxing** [comment]
统一业务code处理，建议自定义解析器，详情看这里https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser

账号过期问题，建议使用拦截器，参看Demo里的TokenInterceptor

**Comment by liujingxing** [comment]
RxHttp暂时还未适配okhttp 4.x版本，目前建议使用3.x版本

**Comment by caiyoufei** [comment]
好的，谢谢大佬 @liujingxing
