### ISSUE TITLE
xhttp.wrapper.exception.HttpStatusCodeException: Method=POST Code=404

### ISSUE THREAD

**Issue by zhuangzeqin** [liujingxing/okhttp-RxHttp#74]
xhttp.wrapper.exception.HttpStatusCodeException: Method=POST Code=404

**Comment by liujingxing** [comment]
404 接口不存在，，有什么问题吗？

**Comment by zhuangzeqin** [comment]
接口存在的我在另外一个项目使用过正常的；参数是经过加密之后； 就显示这个40403-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: rxhttp.wrapper.exception.HttpStatusCodeException: Method=POST Code=404
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: message = Not Found
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: http://agentapi2.sqianbao.cn/agentApi2/login/
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: userName=13888888888&password=abc888888&agentOem=200010&agentNo=10012
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Date: Fri, 06 Mar 2020 04:34:43 GMT
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Content-Type: text/html
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Content-Length: 262
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Connection: keep-alive
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Set-Cookie: aliyungf_tc=AQAAANUY3SQqHQoA2oPvtyT2PLefAG+o; Path=/; HttpOnly
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Expires: 0
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Cache-control: private
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err: Sorry, Page Not Found��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at rxhttp.wrapper.exception.ExceptionHelper.throwIfFatal(ExceptionHelper.java:30)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at rxhttp.wrapper.parse.Parser$-CC.$default$convert(Parser.java:51)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at rxhttp.wrapper.parse.AbstractParser.convert(AbstractParser.java)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at com.eeepay.zzq.rxhttpdemo.parse.ResultCallBackParse.onParse(ResultCallBackParse.java:30)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at rxhttp.ObservableHttp.execute(ObservableHttp.java:116)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:67)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-06 12:34:43.703 7070-7186/com.eeepay.zzq.rxhttpdemo E/RxHttp: rxhttp.wrapper.exception.HttpStatusCodeException: Method=POST Code=404
    message = Not Found
    
    http://agentapi2.sqianbao.cn/agentApi2/login/
    
    userName=13888888888&password=abc888888&agentOem=200010&agentNo=10012
    
    Date: Fri, 06 Mar 2020 04:34:43 GMT
    Content-Type: text/html
    Content-Length: 262
    Connection: keep-alive
    Set-Cookie: aliyungf_tc=AQAAANUY3SQqHQoA2oPvtyT2PLefAG+o; Path=/; HttpOnly
    Expires: 0
    Cache-control: private
    
    Sorry, Page Not Found��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
03-06 12:34:43.703 7070-7070/com.eeepay.zzq.rxhttpdemo D/RxHttp: 回调失败Not Found

**Comment by liujingxing** [comment]
404异常是okhttp抛出来的，所以这个你还得再查查，用postman试试。如果还不行话，加我QQ 327744707  ,把接口及加密方式告诉我，我这边可以帮你调试一下

**Comment by zhuangzeqin** [comment]
已经找打问题了； 是我这边自己的问题；你的框架很好； 使用起来也很方便
