### ISSUE TITLE
老铁能支持二进制请求吗？

### ISSUE THREAD

**Issue by ZQ173** [liujingxing/okhttp-RxHttp#76]
我们后台用的二进制传输，application/octet-stream ，咱框架感觉不错，希望能支持。

**Comment by liujingxing** [comment]
目前你可以通过自定义Param去实现，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param

**Comment by ZQ173** [comment]
好的，3Q。
