### ISSUE TITLE
使用1.4.4 及2.0.0 版本下载文件 偶发性 异常IOException

### ISSUE THREAD

**Issue by jiongjiongxia** [liujingxing/okhttp-RxHttp#77]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/3068542/76967935-126c7d00-6963-11ea-8f31-07b07de76884.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/3068542/76967988-26b07a00-6963-11ea-8a8f-be93f82c70bb.png">
频率大概有10%

**Comment by liujingxing** [comment]
你是断点下载？代码贴一下

**Comment by liujingxing** [comment]
参考下这片文章https://www.jianshu.com/p/8753188b315c

**Comment by jiongjiongxia** [comment]
不是断点下载，就是普通的下载，小文件大文件都有
<img width="796" alt="image" src="https://user-images.githubusercontent.com/3068542/77021146-ea136b80-69c0-11ea-8931-81a2f1a651b2.png">
我也看到你说的那篇文章了，我没用他的方法。我在自定义的Httpclient里加了这个，目前几乎没有重现
OkHttpClient.Builder()
                    **.retryOnConnectionFailure(true)**

**Comment by liujingxing** [comment]
嗯，你这种属于特殊情况，特殊处理下就好了，在okhttp的issue也能找到相同的问题。另外，RxHttp默认在IO线程发起请求，也默认在IO线程回调，所以不用再指定IO线程，如果要指定请求发起线程，请在asXxx方法前调用，asXxx方法后指定无效。
