### ISSUE TITLE
文件下载出现异常

### ISSUE THREAD

**Issue by fengxiaozheng** [liujingxing/okhttp-RxHttp#78]
在带进度下载文件时，出现了空指针异常了：attempt  to read from field 'sun.util.calendar$Date java.util.Date.cdate' on a null object reference.   rxhttp版本为1.4.4

**Comment by liujingxing** [comment]
光这个日志，我看不出具体原因，RxHttp内部也没有用到`java.util.Date.cdate`这个类，贴出详细错误日志

**Comment by fengxiaozheng** [comment]
无法看到详细日志，客户测试发现的。。。只能看到这么多，很难受

**Comment by liujingxing** [comment]
那就要查查自己的代码哪里用到这个类了
