### ISSUE TITLE
多线程并发怎么处理

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#79]
我有两个RxHttp请求，需要拿到这两个请求的回调数据，再执行别的方法，这个怎么操作？

**Comment by liujingxing** [comment]
协程的话看这里  
https://juejin.im/entry/5e780528f265da57563279af

非协程看这里

https://juejin.im/entry/5d0837eef265da1bcb4f2d86

**Comment by chenyinchao** [comment]
非常感谢
