### ISSUE TITLE
希望能优化日志打印

### ISSUE THREAD

**Issue by taoczZYC** [liujingxing/okhttp-RxHttp#80]
目前项目自带的日志打印不是很友好，返回的数据没有什么排版，我只能关掉项目日志，自己拦截后打印

**Comment by liujingxing** [comment]
你指的返回的json数据自动格式化？

**Comment by taoczZYC** [comment]
是的

**Comment by liujingxing** [comment]
logcat对日志打印有长度限制，格式化其实意义不大，后续有时间会考虑开放日志打印接口，供大家自己选择。

**Comment by taoczZYC** [comment]
logcat对日志打印的确是有长度限制，所以现在项目的日志打印会出现打印不全的问题，其实可以借鉴一下开源的日志打印项目，格式化看起来方便也不会打印不全

**Comment by liujingxing** [comment]
好的，感谢提出

**Comment by rabbithgs** [comment]
也希望可以控制打印日志等级

**Comment by liujingxing** [comment]
暂时不打算开放日志打印接口，如果你喜欢RxHttp的日志打印格式，可使用`implementation 'com.squareup.okhttp3:logging-interceptor:4.7.2'`打印，也可自定义拦截器去打印，感谢提出。
