### ISSUE TITLE
RxHttp请求里面执行过程中遇到异常，怎么看堆栈，应该是被try....catch了，我这里都是弹toast，看不到具体log，是哪里crash了，比如数组越界

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#81]

**Comment by liujingxing** [comment]
你说的你自己try..catch ?  那你需要在catch语句里面执行`e.printStackTrace()`才能看到堆栈信息

**Comment by chenyinchao** [comment]
是rxhttp的try...catch，有时候弹了toast不知道是哪个堆栈crash，不方便定位，也可能是getView.handle();  在activity那边crash了，那这个只能在throwable 这个回调里面打log看了
RxHttp.get("http://...")    
    .asString()             
    .subscribe(s -> { 
        //请求成功
        getView.handle();                       
    }, throwable -> {                                  
        //请求失败
       ToastUtils.showShort(throwable.getMessage());                                         
    });

**Comment by liujingxing** [comment]
有堆栈信息的，你找找看
