### ISSUE TITLE
自定义Parser报错

### ISSUE THREAD

**Issue by evil123** [liujingxing/okhttp-RxHttp#83]
生成的rxhttp报错，找不到构造

**Comment by liujingxing** [comment]
需要提供两个构造方法，详情查看 https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser
