### ISSUE TITLE
会考虑支持RxJava3吗?

### ISSUE THREAD

**Issue by BanGyJ** [liujingxing/okhttp-RxHttp#84]

**Comment by liujingxing** [comment]
目前要做的事还很多，一定尽快安排

**Comment by BanGyJ** [comment]
> 目前要做的事还很多，一定尽快安排

好的,期待下

**Comment by liujingxing** [comment]
RxHttp v2.2.0版本已支持RxJava3，详情查看https://github.com/liujingxing/okhttp-RxHttp
