### ISSUE TITLE
混淆规则

### ISSUE THREAD

**Issue by Harlber** [liujingxing/okhttp-RxHttp#86]
```java
android {
    defaultConfig {
        consumerProguardFiles 'proguard-rules.pro'
    }
}
```

在库中配置consumerProguardFiles，将`-keep class rxhttp.**{*;}`写进去，打包会自动合并到业务层Proguard文件中，这样在对外发布版本时就不需要提供混淆规则

**Comment by liujingxing** [comment]
还有这种操作，学习了。不过好像没有必要，RxHttp可混淆，也可不混淆，这个取决于开发者。
