### ISSUE TITLE
如何重新发起请求，不改变原请求参数，只是在header里添加token

### ISSUE THREAD

**Issue by yxAnswer** [liujingxing/okhttp-RxHttp#88]

**Comment by liujingxing** [comment]
看这里https://github.com/liujingxing/okhttp-RxHttp/blob/master/app/src/main/java/com/example/httpsender/interceptor/TokenInterceptor.java

**Comment by Jasperben** [comment]
@liujingxing intercept是否可以拦截响应数据的code  不拦截响应头

**Comment by liujingxing** [comment]
> @liujingxing intercept是否可以拦截响应数据的code  不拦截响应头
> 

可以，但需要注意的是body只能读取一次，网上有很多案例
