### ISSUE TITLE
关闭请求的处理方式

### ISSUE THREAD

**Issue by edifangyi** [liujingxing/okhttp-RxHttp#90]
disposable.dispose()

希望专门提供一个方法可以关闭
RxHttp.cancelSubscription(disposable);

**Comment by liujingxing** [comment]
好的

**Comment by liujingxing** [comment]
RxHttp v2.2.0版本已加入 两个静态方法   `RxHttp.dispose(Disposable)`、RxHttp.isDisposed(Disposable)
