### ISSUE TITLE
kotlin项目，引入最新2.1.1版本，clean之后rebuild

### ISSUE THREAD

**Issue by linmomo** [liujingxing/okhttp-RxHttp#92]
![image](https://user-images.githubusercontent.com/13284924/79412325-c3ece580-7fd7-11ea-9853-289e911d104b.png)
![image](https://user-images.githubusercontent.com/13284924/79412337-ca7b5d00-7fd7-11ea-8e24-ac98952f9f69.png)
项目已经有引入注解了，低版本没这个问题，还是姿势不对

**Comment by liujingxing** [comment]
依赖`rxhttp-compiler`用的kapt还是annotationProcessor？

**Comment by linmomo** [comment]
![image](https://user-images.githubusercontent.com/13284924/79413623-08c64b80-7fdb-11ea-8e46-9d7ab5939de2.png)
![image](https://user-images.githubusercontent.com/13284924/79413631-0e239600-7fdb-11ea-960b-747579acd78f.png)
![image](https://user-images.githubusercontent.com/13284924/79413643-18459480-7fdb-11ea-871e-93fdbd69fda2.png)
按照文档配置，还没开始用，就配了一个默认域名，编译不通过

**Comment by linmomo** [comment]
![image](https://user-images.githubusercontent.com/13284924/79416514-6f9b3300-7fe2-11ea-9591-5233fe13bef6.png)
kotlin扩展函数问题

**Comment by liujingxing** [comment]
新版本只需要ResponseParser就好了，详情查看https://github.com/liujingxing/okhttp-RxHttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser

**Comment by linmomo** [comment]
感谢作者，老版本升级上来，多了ListParser，所以会有问题，去掉就行了，问题已解决
