### ISSUE TITLE
android studio 3.5引入2.1.1 运行报冲突

### ISSUE THREAD

**Issue by zhangheshuai** [liujingxing/okhttp-RxHttp#93]
android studio 3.5引入报冲突

**Comment by liujingxing** [comment]
具体什么问题？

**Comment by zhangheshuai** [comment]
More than one file was found with OS independent path 'META-INF/proguard/coroutines.pro' 
网上有解决方案 但是我不确定哪一个冲突 1.4.0版本没有问题 还有就是android studio 3.6就没有问题

**Comment by liujingxing** [comment]
rxhttp 2.x版本引入了协程，估计跟其它依赖了协程的库引发的冲突。按网上的解决方法，或者升级as 3.6

**Comment by zhangheshuai** [comment]
好的 谢谢
