### ISSUE TITLE
请问在module中引用了rxhttp 和rxhttp-compiler

### ISSUE THREAD

**Issue by qq570026938** [liujingxing/okhttp-RxHttp#94]
如果在module中配置了rxhttp 和rxhttp-compiler我在主工程配置baseurl无法生效，该怎么处理，kapt注解的只能在本module用吗，有没有方法也可以在主工程用

**Comment by liujingxing** [comment]
kapt 可以在任意module中用，但是只会在本module检索注解；对于你的情况，你可以在baseModule依赖RxHttp，其它module依赖baseModule就好了

**Comment by qq570026938** [comment]
好吧，我确实是想做个basemodule 但是不想别的项目引用这个module的时候，每次改这个module里面的内容，哈哈

**Comment by liujingxing** [comment]
这个我没办法，注解处理器只会检索本module的注解。

**Comment by qq570026938** [comment]
好的
