### ISSUE TITLE
像这种数据格式的如何使用RxHttp？

### ISSUE THREAD

**Issue by chenyusheng** [liujingxing/okhttp-RxHttp#96]
`{\"msg\":\"Incorrect Verification Code\",\"code\":-1}`

目前我用 toStr( )是可以获取到数据，但是 asResponse( )就一直会抛错，换FastJsonConverter 也不行，虽然大概猜到是 \" 的锅，但是不大清楚可能怎么处理？

**Comment by chenyusheng** [comment]
{\"msg\":\"Incorrect Verification Code\",\"code\":-1}

**Comment by chenyusheng** [comment]
`{\"msg\":\"Incorrect Verification Code\",\"code\":-1}`

**Comment by liujingxing** [comment]
https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ    第10条

**Comment by chenyusheng** [comment]
我有使用 ResponseParser 了的,我觉得可能还是  `\"` 的锅

**Comment by liujingxing** [comment]
`\"`服务端返回就有斜杠？还是你复制出来后自动加上的？如果是服务端返回就有，那就是格式不对
