### ISSUE TITLE
组件化问题

### ISSUE THREAD

**Issue by ydmmocoo** [liujingxing/okhttp-RxHttp#99]
比如我有项目:APP<---组件A(可能有很多组件)<---CommonLibrary,其中CommonLibrary依赖了implementation 'com.ljx.rxhttp:rxhttp:2.2.0'，annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.2.0' ，implementation 'io.reactivex.rxjava3:rxjava:3.0.2'， implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'， implementation 'com.ljx.rxlife3:rxlife-rxjava:3.0.0' 。我在CommonLibrary中指定了baseUrl，并加上了@DefaultDomain注解，还创建了ResponseParser类，也加上了@Parser(name = "Response")注解(也在App的Moudule,组件A的Module,CommonLibrary的Module中加了arguments = [rxhttp_rxjava: 'rxjava3']，并且Rebuild了项目)，在组件A中还是无法找到asResponse，并且也提示没有指定baseUrl，as(RxLife.as(this))也找不到，其他asString等相关方法可以找到。请问这是什么原因？是我项目配置错误，还是其他原因，请指教一下，谢谢！

**Comment by ydmmocoo** [comment]
每个Module也都有依赖annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.2.0'

**Comment by liujingxing** [comment]
注解处理器只会在本Module检索注解；你只需要在CommonLibrary依赖RxHttp相关库即可，`arguments = [rxhttp_rxjava: 'rxjava3']`也是在CommonLibrary配置即可。
